/* Generated by bases.mjs from templates-base/ — do not edit, edit the JSON and re-run.
   3 templates, each one checked for duplicate ids, unresolved
   needs, cycles, missing palette colours, non-numeric costs and rootlessness
   before it got here. */
window.BASES = [
 {
  "id": "blank",
  "name": "Start from four",
  "note": "The smallest board that runs. Four roots, nothing downstream, and a fifth slot that needs two of them — which is the whole lesson from the minimum-cycle entry expressed as the shortest possible file. Copy it, rename it, and add rows. The generator will tell you if the graph you wrote has a cycle in it, references a sector that does not exist, or has no roots at all, so the failure mode is a build error rather than a board that silently does nothing.",
  "plate": {
   "cols": 3,
   "gap": 118,
   "size": 380,
   "tower": "spire"
  },
  "palette": {
   "demand": "rgb(201,138,127)",
   "water": "rgb(110,198,255)",
   "shelter": "rgb(232,192,105)",
   "commons": "rgb(111,192,138)",
   "food": "rgb(159,214,120)"
  },
  "sectors": [
   {
    "id": "want",
    "name": "Want",
    "sector": "demand",
    "glyph": "❦",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 2
    },
    "build": 15,
    "why": "A root. Something has to be wanted or nothing downstream has a reason to exist."
   },
   {
    "id": "wet",
    "name": "Water",
    "sector": "water",
    "glyph": "≋",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 8
    },
    "build": 30,
    "why": "A root. Decide where the water is before you decide anything else, because everything else is sited relative to it."
   },
   {
    "id": "roof",
    "name": "Roof",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 25,
    "why": "A root. Somewhere that is the same place tomorrow — everything else needs an address."
   },
   {
    "id": "rest",
    "name": "The rest",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "A root, and the odd one: it does not grow when the others do. It is what the others are spending, and its health cannot be read off its own activity because its activity is that nothing is happening."
   },
   {
    "id": "food",
    "name": "Food",
    "sector": "food",
    "glyph": "✿",
    "root": false,
    "needs": [
     "wet",
     "roof"
    ],
    "cost": {
     "pw": 14,
     "wa": 300
    },
    "build": 60,
    "why": "The first thing that is not a root, and the point of the file. It needs two of them at once — which is why a board full of roots produces nothing and the shortest closed loop is the thing to look for rather than the most important node."
   }
  ],
  "_stats": {
   "sectors": 5,
   "roots": 4,
   "depth": 2,
   "width": 4
  }
 },
 {
  "id": "hellenic",
  "name": "The Hellenic Twelve",
  "note": "The default. Twelve sectors in the order economy.html worked out, each one unable to start until the thing that feeds it is running. Extracted from the game rather than retyped, so it is exactly what shipped.",
  "plate": {
   "cols": 4,
   "gap": 108,
   "size": 460,
   "tower": "block"
  },
  "palette": {
   "demand": "rgb(201,138,127)",
   "water": "rgb(110,198,255)",
   "shelter": "rgb(232,192,105)",
   "commons": "rgb(111,192,138)",
   "food": "rgb(159,214,120)",
   "forge": "rgb(224,140,90)",
   "skill": "rgb(157,138,224)",
   "force": "rgb(224,112,90)",
   "trade": "rgb(110,198,255)",
   "records": "rgb(232,192,105)",
   "contract": "rgb(180,170,200)",
   "authority": "rgb(240,200,90)"
  },
  "sectors": [
   {
    "id": "aphro",
    "name": "Aphrodite",
    "sector": "demand",
    "glyph": "❦",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 2
    },
    "build": 20,
    "why": "Desire is a root, not a luxury. Nobody farms without wanting something, and an economy with no demand in it is not early — it is stopped."
   },
   {
    "id": "posei",
    "name": "Poseidon",
    "sector": "water",
    "glyph": "≋",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 8
    },
    "build": 40,
    "why": "Water and the routes over it. Nothing else is a root because nothing else can be: no agriculture, no settlement, no transport until you have decided where the water is."
   },
   {
    "id": "hesti",
    "name": "Hestia",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 35,
    "why": "The hearth. Somewhere warm that is the same place tomorrow. First in the old rites for the same reason it is a root here — everything else needs an address."
   },
   {
    "id": "artem",
    "name": "Artemis",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "The un-farmed. The only sector that does not grow when the others do — she is what the rest are spending, and her health cannot be read off her own activity, because her activity is that nothing is happening."
   },
   {
    "id": "demet",
    "name": "Demeter",
    "sector": "food",
    "glyph": "✿",
    "needs": [
     "posei"
    ],
    "cost": {
     "pw": 14,
     "wa": 400
    },
    "build": 90,
    "why": "Grain, and therefore surplus, and therefore every hand not growing food. She needs water. Almost everything else needs her."
   },
   {
    "id": "hepha",
    "name": "Hephaestus",
    "sector": "forge",
    "glyph": "⚒",
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 26
    },
    "build": 110,
    "why": "Tools, and tools that make tools. Cannot start until somebody has enough food that a pair of hands can be spared from growing it — the forge is paid for in meals somebody else grew."
   },
   {
    "id": "athen",
    "name": "Athena",
    "sector": "skill",
    "glyph": "◈",
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 12
    },
    "build": 80,
    "why": "Craft, and the passing of it on. A day spent teaching is a day not spent growing, and every apprenticeship in history was funded that way whether or not anybody said so."
   },
   {
    "id": "ares",
    "name": "Ares",
    "sector": "force",
    "glyph": "⚔",
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 18
    },
    "build": 70,
    "why": "Force, under its own name, and downstream of the surplus — it needs something worth taking. A restart that budgets security before it has anything to secure has described a garrison."
   },
   {
    "id": "herme",
    "name": "Hermes",
    "sector": "trade",
    "glyph": "⇌",
    "needs": [
     "hepha",
     "demet"
    ],
    "cost": {
     "pw": 16
    },
    "build": 100,
    "why": "Roads, exchange, messages. Needs two producers with different surpluses; with one producer there is no market, only a stall."
   },
   {
    "id": "apoll",
    "name": "Apollo",
    "sector": "records",
    "glyph": "☉",
    "needs": [
     "herme"
    ],
    "cost": {
     "pw": 10
    },
    "build": 85,
    "why": "Measure, standards, the written account — and he comes AFTER trade. Cuneiform begins as barley tallies, not poetry. The ledger is downstream of the exchange and the first thing anybody wrote was a receipt."
   },
   {
    "id": "hera",
    "name": "Hera",
    "sector": "contract",
    "glyph": "⊗",
    "needs": [
     "apoll"
    ],
    "cost": {
     "pw": 8
    },
    "build": 75,
    "why": "Oath, and the binding of an agreement past the moment of making it. Needs the record: an oath nobody can produce is a memory, and two memories that disagree is the condition contract law exists to end."
   },
   {
    "id": "zeus",
    "name": "Zeus",
    "sector": "authority",
    "glyph": "⚡",
    "needs": [
     "hera",
     "apoll"
    ],
    "cost": {
     "pw": 20
    },
    "build": 120,
    "why": "The appeal of last resort, and the only sector that contributes nothing until two others are already running. You cannot adjudicate without a rule AND a record — with the rule alone you have authority ruling by memory."
   }
  ],
  "_stats": {
   "sectors": 12,
   "roots": 4,
   "depth": 7,
   "width": 4
  }
 },
 {
  "id": "sumerian",
  "name": "The Sumerian Eleven",
  "note": "The same economy fifteen hundred years earlier, and it is not a reskin — the graph is a different SHAPE. Nisaba holds grain and writing together, so two Hellenic nodes collapse into one and the record arrives at the same moment as the surplus rather than after the market. Authority splits the other way: An is rank with nothing to act on and Enlil is the half that does something, so where the Hellenic board has one Zeus this one has a figurehead and an executive, and only the second is downstream of anything. Eleven nodes, not twelve, and the count is the finding. Mappings follow sumer.html where that page states them; where it does not, the choice is marked in the why and is meant to be argued with — that is what an editable template is for.",
  "plate": {
   "cols": 4,
   "gap": 108,
   "size": 460,
   "tower": "drum"
  },
  "palette": {
   "demand": "rgb(214,150,120)",
   "water": "rgb(120,190,220)",
   "shelter": "rgb(210,180,120)",
   "commons": "rgb(130,185,140)",
   "food": "rgb(190,200,110)",
   "forge": "rgb(214,130,80)",
   "skill": "rgb(170,150,215)",
   "force": "rgb(210,105,85)",
   "trade": "rgb(140,190,205)",
   "records": "rgb(200,180,130)",
   "contract": "rgb(185,175,195)",
   "authority": "rgb(230,195,105)"
  },
  "sectors": [
   {
    "id": "inan",
    "name": "Inanna",
    "sector": "demand",
    "glyph": "✦",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 2
    },
    "build": 20,
    "why": "Wanting, and she is also the planet you are standing on — Inanna is Venus, and was before anybody called it that in Latin. Desire is a root here for the same reason it is a root anywhere: nobody farms without wanting something."
   },
   {
    "id": "enki",
    "name": "Enki",
    "sector": "water",
    "glyph": "≋",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 8
    },
    "build": 40,
    "why": "The fresh water under everything, and the keeper of the me — the itemised list of the components of civilisation. Water first, because nothing sites itself before somebody has decided where the water is."
   },
   {
    "id": "ninh",
    "name": "Ninhursag",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 35,
    "why": "The foothills and the ground itself. Shelter is a root because everything else needs an address, and this roster puts that in the earth rather than in a hearth."
   },
   {
    "id": "nins",
    "name": "Ninshubur",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "Inanna's messenger, and the one sent between powers when something has to move that nobody owns. Placed on the commons because that is the sector whose health cannot be read off its own activity — her activity is that nothing has gone wrong yet."
   },
   {
    "id": "nisa",
    "name": "Nisaba",
    "sector": "food",
    "glyph": "𒀭",
    "root": false,
    "needs": [
     "enki"
    ],
    "cost": {
     "pw": 14,
     "wa": 400
    },
    "build": 90,
    "why": "Grain AND writing, in one hand, which is the whole difference between this board and the Hellenic one. Two nodes there, one here — and the consequence is that the record does not have to wait for a market, because the person counting the barley is already the person who writes."
   },
   {
    "id": "nina",
    "name": "Ninagal",
    "sector": "forge",
    "glyph": "⚒",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 26
    },
    "build": 110,
    "why": "Enki's smith. Downstream of the surplus for the same reason every forge is: the hands at the fire are hands not growing food, and somebody else grew it."
   },
   {
    "id": "enk2",
    "name": "The me",
    "sector": "skill",
    "glyph": "◈",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 12
    },
    "build": 80,
    "why": "Enki's decrees — a list, itemised, of the components of civilisation, and Inanna takes them from him to Uruk. Craft as a transferable inventory rather than as a talent, which is a genuinely different theory of skill from Athena's and is why it gets its own node."
   },
   {
    "id": "ninu",
    "name": "Ninurta",
    "sector": "force",
    "glyph": "⚔",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 18
    },
    "build": 70,
    "why": "Plough and war in one figure, which is more honest than separating them. Downstream of the surplus, because force needs something worth taking before it is worth budgeting for."
   },
   {
    "id": "nsh2",
    "name": "The errand",
    "sector": "trade",
    "glyph": "⇌",
    "root": false,
    "needs": [
     "nina",
     "nisa"
    ],
    "cost": {
     "pw": 16
    },
    "build": 100,
    "why": "Ninshubur again, in her other function: the one sent between powers. Needs two producers with different surpluses — with one producer there is no market, only a stall. MARKED: sumer.html does not assign trade explicitly and this is the defensible reading, not a stated one."
   },
   {
    "id": "utu",
    "name": "Utu",
    "sector": "contract",
    "glyph": "☉",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 8
    },
    "build": 75,
    "why": "The sun, who sees everything, and therefore justice and the oath. He needs the record and the record is Nisaba — but Nisaba is already running by the time anybody has eaten, so on this board the oath is available far earlier than it is on the Hellenic one. That is the shape change, stated as a dependency."
   },
   {
    "id": "anen",
    "name": "An · Enlil",
    "sector": "authority",
    "glyph": "⚡",
    "root": false,
    "needs": [
     "utu"
    ],
    "cost": {
     "pw": 20
    },
    "build": 120,
    "why": "One node holding a split. An is the sky and the highest authority and does essentially nothing; Enlil is the half that acts, and only that half is downstream of anything. Where the Hellenic board needs a rule AND a record before authority can adjudicate, this one needs the oath alone — because the record came with the grain."
   }
  ],
  "_stats": {
   "sectors": 11,
   "roots": 4,
   "depth": 4,
   "width": 4
  }
 }
];
