/* Generated by bases.mjs from templates-base/ — do not edit, edit the JSON and re-run.
   4 templates, each one checked for duplicate ids, unresolved
   needs, cycles, missing palette colours, non-numeric costs and rootlessness
   before it got here. */
window.BASES = [
 {
  "id": "arrival",
  "name": "The Spread — arrival, with a writing station first",
  "note": "The answer to 'what is the first thing you would need to do', and it inverts the Hellenic board rather than reskinning it. There, records comes AFTER trade: cuneiform begins as barley tallies, the ledger is downstream of the exchange, and the first thing anybody wrote was a receipt for something that already had a market. That is true when you GROW a surplus from nothing. It is false when you ARRIVE with one. Land with a forest and colonists and the very first thing you need is a writing station, because you already have a spread and nobody knows what is in it, who brought it, or what is owed on it — and every allocation you make before that is a guess you cannot audit later. So here the record is a root and almost everything hangs off it. Same twelve sectors, same twelve names, opposite build order, and the difference is entirely in what you were handed on day one.",
  "plate": {
   "cols": 4,
   "gap": 106,
   "size": 460,
   "tower": "block"
  },
  "palette": {
   "records": "rgb(255,230,168)",
   "commons": "rgb(111,192,138)",
   "shelter": "rgb(232,192,105)",
   "food": "rgb(159,214,120)",
   "demand": "rgb(201,138,127)",
   "water": "rgb(110,198,255)",
   "contract": "rgb(180,170,200)",
   "trade": "rgb(95,211,224)",
   "skill": "rgb(157,138,224)",
   "forge": "rgb(224,140,90)",
   "force": "rgb(224,112,90)",
   "authority": "rgb(240,200,90)"
  },
  "sectors": [
   {
    "id": "apoll",
    "name": "The writing station",
    "sector": "records",
    "glyph": "☉",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 4
    },
    "build": 25,
    "why": "First, and it is first because you arrived with things. A tally of what is in the spread, who carried it, and what is owed on it. Every allocation made before this one is a guess you cannot audit afterwards, and the whole reason writing exists is that somebody had a heap and needed to say how big it was without moving it."
   },
   {
    "id": "artem",
    "name": "The forest",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "You have it. That is the difference between this board and the other one — the commons is not something you protect on the way to building an economy, it is the asset you landed on top of, and it starts full and only goes one way unless somebody spends a window on it."
   },
   {
    "id": "hesti",
    "name": "The colonists",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 30,
    "why": "They came with you and they need an address before they need anything else. A root here for the same reason it is a root anywhere, except that on this board the people exist before the shelter does, which is the wrong way round and is exactly the pressure you are under."
   },
   {
    "id": "demet",
    "name": "Stores",
    "sector": "food",
    "glyph": "✿",
    "root": false,
    "needs": [
     "apoll"
    ],
    "cost": {
     "pw": 10,
     "wa": 200
    },
    "build": 55,
    "why": "Not grown — counted. The food came off the ship and the only question is how long it lasts, which is a question the writing station answers and nothing else can. Rationing without a tally is not rationing, it is hoping."
   },
   {
    "id": "posei",
    "name": "Water",
    "sector": "water",
    "glyph": "≋",
    "root": false,
    "needs": [
     "apoll"
    ],
    "cost": {
     "pw": 8
    },
    "build": 45,
    "why": "Downstream of the record here, which looks wrong until you notice you are siting a waterway inside a forest that already exists. You are not choosing where the water goes; you are finding out where it already is and writing it down."
   },
   {
    "id": "hera",
    "name": "Standing",
    "sector": "contract",
    "glyph": "⊗",
    "root": false,
    "needs": [
     "apoll",
     "hesti"
    ],
    "cost": {
     "pw": 8
    },
    "build": 65,
    "why": "Who is owed what, binding past the moment of saying it. It arrives early on this board and late on the other one, and the reason is the same reason: an oath needs a record, and here the record was the first thing built."
   },
   {
    "id": "aphro",
    "name": "Want",
    "sector": "demand",
    "glyph": "❦",
    "root": false,
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 2
    },
    "build": 25,
    "why": "A root on the Hellenic board and not one here, which is the sharpest single difference between them. When you arrive with stores, nobody wants anything for a while — demand appears the moment the counted pile visibly stops being enough, and not one day before."
   },
   {
    "id": "athen",
    "name": "Skill",
    "sector": "skill",
    "glyph": "◈",
    "root": false,
    "needs": [
     "hera"
    ],
    "cost": {
     "pw": 12
    },
    "build": 70,
    "why": "Teaching is a day not spent doing, which is affordable only once somebody can say whose day it was. Downstream of standing rather than of food, because on this board the constraint is not calories, it is who is entitled to spend the hour."
   },
   {
    "id": "herme",
    "name": "Exchange",
    "sector": "trade",
    "glyph": "⇌",
    "root": false,
    "needs": [
     "aphro",
     "hera"
    ],
    "cost": {
     "pw": 14
    },
    "build": 80,
    "why": "Needs somebody to want something and a way to bind the deal. Late here, and it is the node that shows the inversion most plainly: on the Hellenic board trade comes before the ledger and here it comes two ranks after it."
   },
   {
    "id": "hepha",
    "name": "Forge",
    "sector": "forge",
    "glyph": "⚒",
    "root": false,
    "needs": [
     "herme",
     "posei"
    ],
    "cost": {
     "pw": 24
    },
    "build": 100,
    "why": "Tools that make tools, and it needs both a market to be worth supplying and water to work with. The first thing on this board that could not have come off the ship."
   },
   {
    "id": "ares",
    "name": "Force",
    "sector": "force",
    "glyph": "⚔",
    "root": false,
    "needs": [
     "herme"
    ],
    "cost": {
     "pw": 18
    },
    "build": 70,
    "why": "Downstream of the exchange, because force needs something worth taking and a spread nobody trades is a spread nobody has priced. A settlement that budgets security before it has a market has described a garrison."
   },
   {
    "id": "zeus",
    "name": "Appeal",
    "sector": "authority",
    "glyph": "⚡",
    "root": false,
    "needs": [
     "hera",
     "athen"
    ],
    "cost": {
     "pw": 20
    },
    "build": 110,
    "why": "The last resort, and it still cannot come first. It needs the binding and it needs somebody trained to read it — a rule with nobody able to interpret it is authority ruling by memory, which is the failure this node exists to prevent on either board."
   }
  ],
  "_stats": {
   "sectors": 12,
   "roots": 3,
   "depth": 5,
   "width": 3
  }
 },
 {
  "id": "blank",
  "name": "Start from four",
  "note": "The smallest board that runs. Four roots, nothing downstream, and a fifth slot that needs two of them — which is the whole lesson from the minimum-cycle entry expressed as the shortest possible file. Copy it, rename it, and add rows. The generator will tell you if the graph you wrote has a cycle in it, references a sector that does not exist, or has no roots at all, so the failure mode is a build error rather than a board that silently does nothing.",
  "plate": {
   "cols": 3,
   "gap": 118,
   "size": 380,
   "tower": "spire"
  },
  "palette": {
   "demand": "rgb(201,138,127)",
   "water": "rgb(110,198,255)",
   "shelter": "rgb(232,192,105)",
   "commons": "rgb(111,192,138)",
   "food": "rgb(159,214,120)"
  },
  "sectors": [
   {
    "id": "want",
    "name": "Want",
    "sector": "demand",
    "glyph": "❦",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 2
    },
    "build": 15,
    "why": "A root. Something has to be wanted or nothing downstream has a reason to exist."
   },
   {
    "id": "wet",
    "name": "Water",
    "sector": "water",
    "glyph": "≋",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 8
    },
    "build": 30,
    "why": "A root. Decide where the water is before you decide anything else, because everything else is sited relative to it."
   },
   {
    "id": "roof",
    "name": "Roof",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 25,
    "why": "A root. Somewhere that is the same place tomorrow — everything else needs an address."
   },
   {
    "id": "rest",
    "name": "The rest",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "A root, and the odd one: it does not grow when the others do. It is what the others are spending, and its health cannot be read off its own activity because its activity is that nothing is happening."
   },
   {
    "id": "food",
    "name": "Food",
    "sector": "food",
    "glyph": "✿",
    "root": false,
    "needs": [
     "wet",
     "roof"
    ],
    "cost": {
     "pw": 14,
     "wa": 300
    },
    "build": 60,
    "why": "The first thing that is not a root, and the point of the file. It needs two of them at once — which is why a board full of roots produces nothing and the shortest closed loop is the thing to look for rather than the most important node."
   }
  ],
  "_stats": {
   "sectors": 5,
   "roots": 4,
   "depth": 2,
   "width": 4
  }
 },
 {
  "id": "hellenic",
  "name": "The Hellenic Twelve",
  "note": "The default. Twelve sectors in the order economy.html worked out, each one unable to start until the thing that feeds it is running. Extracted from the game rather than retyped, so it is exactly what shipped.",
  "plate": {
   "cols": 4,
   "gap": 108,
   "size": 460,
   "tower": "block"
  },
  "palette": {
   "demand": "rgb(201,138,127)",
   "water": "rgb(110,198,255)",
   "shelter": "rgb(232,192,105)",
   "commons": "rgb(111,192,138)",
   "food": "rgb(159,214,120)",
   "forge": "rgb(224,140,90)",
   "skill": "rgb(157,138,224)",
   "force": "rgb(224,112,90)",
   "trade": "rgb(110,198,255)",
   "records": "rgb(232,192,105)",
   "contract": "rgb(180,170,200)",
   "authority": "rgb(240,200,90)"
  },
  "sectors": [
   {
    "id": "aphro",
    "name": "Aphrodite",
    "sector": "demand",
    "glyph": "❦",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 2
    },
    "build": 20,
    "why": "Desire is a root, not a luxury. Nobody farms without wanting something, and an economy with no demand in it is not early — it is stopped."
   },
   {
    "id": "posei",
    "name": "Poseidon",
    "sector": "water",
    "glyph": "≋",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 8
    },
    "build": 40,
    "why": "Water and the routes over it. Nothing else is a root because nothing else can be: no agriculture, no settlement, no transport until you have decided where the water is."
   },
   {
    "id": "hesti",
    "name": "Hestia",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 35,
    "why": "The hearth. Somewhere warm that is the same place tomorrow. First in the old rites for the same reason it is a root here — everything else needs an address."
   },
   {
    "id": "artem",
    "name": "Artemis",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "The un-farmed. The only sector that does not grow when the others do — she is what the rest are spending, and her health cannot be read off her own activity, because her activity is that nothing is happening."
   },
   {
    "id": "demet",
    "name": "Demeter",
    "sector": "food",
    "glyph": "✿",
    "needs": [
     "posei"
    ],
    "cost": {
     "pw": 14,
     "wa": 400
    },
    "build": 90,
    "why": "Grain, and therefore surplus, and therefore every hand not growing food. She needs water. Almost everything else needs her."
   },
   {
    "id": "hepha",
    "name": "Hephaestus",
    "sector": "forge",
    "glyph": "⚒",
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 26
    },
    "build": 110,
    "why": "Tools, and tools that make tools. Cannot start until somebody has enough food that a pair of hands can be spared from growing it — the forge is paid for in meals somebody else grew."
   },
   {
    "id": "athen",
    "name": "Athena",
    "sector": "skill",
    "glyph": "◈",
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 12
    },
    "build": 80,
    "why": "Craft, and the passing of it on. A day spent teaching is a day not spent growing, and every apprenticeship in history was funded that way whether or not anybody said so."
   },
   {
    "id": "ares",
    "name": "Ares",
    "sector": "force",
    "glyph": "⚔",
    "needs": [
     "demet"
    ],
    "cost": {
     "pw": 18
    },
    "build": 70,
    "why": "Force, under its own name, and downstream of the surplus — it needs something worth taking. A restart that budgets security before it has anything to secure has described a garrison."
   },
   {
    "id": "herme",
    "name": "Hermes",
    "sector": "trade",
    "glyph": "⇌",
    "needs": [
     "hepha",
     "demet"
    ],
    "cost": {
     "pw": 16
    },
    "build": 100,
    "why": "Roads, exchange, messages. Needs two producers with different surpluses; with one producer there is no market, only a stall."
   },
   {
    "id": "apoll",
    "name": "Apollo",
    "sector": "records",
    "glyph": "☉",
    "needs": [
     "herme"
    ],
    "cost": {
     "pw": 10
    },
    "build": 85,
    "why": "Measure, standards, the written account — and he comes AFTER trade. Cuneiform begins as barley tallies, not poetry. The ledger is downstream of the exchange and the first thing anybody wrote was a receipt."
   },
   {
    "id": "hera",
    "name": "Hera",
    "sector": "contract",
    "glyph": "⊗",
    "needs": [
     "apoll"
    ],
    "cost": {
     "pw": 8
    },
    "build": 75,
    "why": "Oath, and the binding of an agreement past the moment of making it. Needs the record: an oath nobody can produce is a memory, and two memories that disagree is the condition contract law exists to end."
   },
   {
    "id": "zeus",
    "name": "Zeus",
    "sector": "authority",
    "glyph": "⚡",
    "needs": [
     "hera",
     "apoll"
    ],
    "cost": {
     "pw": 20
    },
    "build": 120,
    "why": "The appeal of last resort, and the only sector that contributes nothing until two others are already running. You cannot adjudicate without a rule AND a record — with the rule alone you have authority ruling by memory."
   }
  ],
  "_stats": {
   "sectors": 12,
   "roots": 4,
   "depth": 7,
   "width": 4
  }
 },
 {
  "id": "sumerian",
  "name": "The Sumerian Eleven",
  "note": "The same economy fifteen hundred years earlier, and it is not a reskin — the graph is a different SHAPE. Nisaba holds grain and writing together, so two Hellenic nodes collapse into one and the record arrives at the same moment as the surplus rather than after the market. Authority splits the other way: An is rank with nothing to act on and Enlil is the half that does something, so where the Hellenic board has one Zeus this one has a figurehead and an executive, and only the second is downstream of anything. Eleven nodes, not twelve, and the count is the finding. Mappings follow sumer.html where that page states them; where it does not, the choice is marked in the why and is meant to be argued with — that is what an editable template is for.",
  "plate": {
   "cols": 4,
   "gap": 108,
   "size": 460,
   "tower": "drum"
  },
  "palette": {
   "demand": "rgb(214,150,120)",
   "water": "rgb(120,190,220)",
   "shelter": "rgb(210,180,120)",
   "commons": "rgb(130,185,140)",
   "food": "rgb(190,200,110)",
   "forge": "rgb(214,130,80)",
   "skill": "rgb(170,150,215)",
   "force": "rgb(210,105,85)",
   "trade": "rgb(140,190,205)",
   "records": "rgb(200,180,130)",
   "contract": "rgb(185,175,195)",
   "authority": "rgb(230,195,105)"
  },
  "sectors": [
   {
    "id": "inan",
    "name": "Inanna",
    "sector": "demand",
    "glyph": "✦",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 2
    },
    "build": 20,
    "why": "Wanting, and she is also the planet you are standing on — Inanna is Venus, and was before anybody called it that in Latin. Desire is a root here for the same reason it is a root anywhere: nobody farms without wanting something."
   },
   {
    "id": "enki",
    "name": "Enki",
    "sector": "water",
    "glyph": "≋",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 8
    },
    "build": 40,
    "why": "The fresh water under everything, and the keeper of the me — the itemised list of the components of civilisation. Water first, because nothing sites itself before somebody has decided where the water is."
   },
   {
    "id": "ninh",
    "name": "Ninhursag",
    "sector": "shelter",
    "glyph": "⌂",
    "root": true,
    "needs": [],
    "cost": {
     "pw": 6
    },
    "build": 35,
    "why": "The foothills and the ground itself. Shelter is a root because everything else needs an address, and this roster puts that in the earth rather than in a hearth."
   },
   {
    "id": "nins",
    "name": "Ninshubur",
    "sector": "commons",
    "glyph": "⌖",
    "root": true,
    "needs": [],
    "cost": {},
    "build": 10,
    "why": "Inanna's messenger, and the one sent between powers when something has to move that nobody owns. Placed on the commons because that is the sector whose health cannot be read off its own activity — her activity is that nothing has gone wrong yet."
   },
   {
    "id": "nisa",
    "name": "Nisaba",
    "sector": "food",
    "glyph": "𒀭",
    "root": false,
    "needs": [
     "enki"
    ],
    "cost": {
     "pw": 14,
     "wa": 400
    },
    "build": 90,
    "why": "Grain AND writing, in one hand, which is the whole difference between this board and the Hellenic one. Two nodes there, one here — and the consequence is that the record does not have to wait for a market, because the person counting the barley is already the person who writes."
   },
   {
    "id": "nina",
    "name": "Ninagal",
    "sector": "forge",
    "glyph": "⚒",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 26
    },
    "build": 110,
    "why": "Enki's smith. Downstream of the surplus for the same reason every forge is: the hands at the fire are hands not growing food, and somebody else grew it."
   },
   {
    "id": "enk2",
    "name": "The me",
    "sector": "skill",
    "glyph": "◈",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 12
    },
    "build": 80,
    "why": "Enki's decrees — a list, itemised, of the components of civilisation, and Inanna takes them from him to Uruk. Craft as a transferable inventory rather than as a talent, which is a genuinely different theory of skill from Athena's and is why it gets its own node."
   },
   {
    "id": "ninu",
    "name": "Ninurta",
    "sector": "force",
    "glyph": "⚔",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 18
    },
    "build": 70,
    "why": "Plough and war in one figure, which is more honest than separating them. Downstream of the surplus, because force needs something worth taking before it is worth budgeting for."
   },
   {
    "id": "nsh2",
    "name": "The errand",
    "sector": "trade",
    "glyph": "⇌",
    "root": false,
    "needs": [
     "nina",
     "nisa"
    ],
    "cost": {
     "pw": 16
    },
    "build": 100,
    "why": "Ninshubur again, in her other function: the one sent between powers. Needs two producers with different surpluses — with one producer there is no market, only a stall. MARKED: sumer.html does not assign trade explicitly and this is the defensible reading, not a stated one."
   },
   {
    "id": "utu",
    "name": "Utu",
    "sector": "contract",
    "glyph": "☉",
    "root": false,
    "needs": [
     "nisa"
    ],
    "cost": {
     "pw": 8
    },
    "build": 75,
    "why": "The sun, who sees everything, and therefore justice and the oath. He needs the record and the record is Nisaba — but Nisaba is already running by the time anybody has eaten, so on this board the oath is available far earlier than it is on the Hellenic one. That is the shape change, stated as a dependency."
   },
   {
    "id": "anen",
    "name": "An · Enlil",
    "sector": "authority",
    "glyph": "⚡",
    "root": false,
    "needs": [
     "utu"
    ],
    "cost": {
     "pw": 20
    },
    "build": 120,
    "why": "One node holding a split. An is the sky and the highest authority and does essentially nothing; Enlil is the half that acts, and only that half is downstream of anything. Where the Hellenic board needs a rule AND a record before authority can adjudicate, this one needs the oath alone — because the record came with the grain."
   }
  ],
  "_stats": {
   "sectors": 11,
   "roots": 4,
   "depth": 4,
   "width": 4
  }
 }
];
