#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   bases.mjs — compiles templates-base/*.json into bases.js, and refuses to
   compile one that is broken.

   Everybody is going to build their own base, which means the failure mode
   that matters is not a bad idea, it is a typo. A sector that needs something
   with a spelling mistake in it is unbuildable forever and the board will not
   say so — it will just sit there looking locked, and the person who wrote it
   will assume they have misunderstood the game. So this checks:

     · every id is unique
     · every `needs` resolves to a real id
     · nothing needs itself, directly or round a loop
     · at least one root exists, and roots need nothing
     · every sector's colour key exists in the palette
     · costs and build times are numbers and not strings

   and prints the graph's depth and its widest rank, because those are the two
   numbers that tell you whether the board you wrote will play.

       node bases.mjs
   ═══════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'templates-base';
const files = readdirSync(DIR).filter((f) => f.endsWith('.json')).sort();
const out = [];
let fatal = 0;

for (const f of files) {
  const t = JSON.parse(readFileSync(join(DIR, f), 'utf8'));
  const errs = [], warn = [];
  const S = t.sectors || [];
  const ids = new Set();

  for (const s of S) {
    if (ids.has(s.id)) errs.push(`duplicate id "${s.id}"`);
    ids.add(s.id);
    if (!s.name) errs.push(`${s.id}: no name`);
    if (!t.palette?.[s.sector]) errs.push(`${s.id}: sector "${s.sector}" has no palette colour`);
    if (typeof s.build !== 'number') errs.push(`${s.id}: build is not a number`);
    for (const [k, v] of Object.entries(s.cost || {}))
      if (typeof v !== 'number') errs.push(`${s.id}: cost.${k} is not a number`);
    if (s.root && (s.needs || []).length) errs.push(`${s.id}: marked root but needs something`);
  }
  for (const s of S)
    for (const n of s.needs || [])
      if (!ids.has(n)) errs.push(`${s.id}: needs "${n}", which does not exist`);

  /* cycles — the one a person cannot see by reading */
  const state = {}, stack = [];
  const walk = (id) => {
    if (state[id] === 2) return;
    if (state[id] === 1) { errs.push(`cycle: ${[...stack, id].join(' → ')}`); return; }
    state[id] = 1; stack.push(id);
    for (const n of (S.find((x) => x.id === id)?.needs || [])) walk(n);
    stack.pop(); state[id] = 2;
  };
  S.forEach((s) => walk(s.id));

  const roots = S.filter((s) => !(s.needs || []).length);
  if (!roots.length) errs.push('no roots — nothing can ever be built');

  /* depth and width: how long the longest chain is, and how many sit at the
     same rank. A deep narrow board is a queue; a wide shallow one is a menu. */
  const depth = {};
  const d = (id) => {
    if (depth[id] != null) return depth[id];
    const s = S.find((x) => x.id === id);
    depth[id] = 1 + Math.max(0, ...(s.needs || []).map(d));
    return depth[id];
  };
  S.forEach((s) => { try { d(s.id) } catch { /* cycle already reported */ } });
  const ranks = {};
  Object.values(depth).forEach((v) => ranks[v] = (ranks[v] || 0) + 1);
  const maxDepth = Math.max(0, ...Object.values(depth));
  const maxRank = Math.max(0, ...Object.values(ranks));

  if (S.length < 4) warn.push('fewer than four sectors — it will play in a minute');
  if (maxDepth < 2) warn.push('every sector is a root — there is no order to discover');

  const tag = errs.length ? 'REFUSED' : 'ok';
  console.log(`${tag.padEnd(8)} ${f.padEnd(16)} ${String(S.length).padStart(2)} sectors · ` +
    `${roots.length} roots · depth ${maxDepth} · widest rank ${maxRank}`);
  errs.forEach((e) => console.log(`         ✗ ${e}`));
  warn.forEach((w) => console.log(`         · ${w}`));
  if (errs.length) { fatal++; continue; }

  t._stats = { sectors: S.length, roots: roots.length, depth: maxDepth, width: maxRank };
  out.push(t);
}

if (fatal) {
  console.log(`\n${fatal} template(s) refused. bases.js not written — a board that ` +
    `cannot be built is worse than no board, because it looks like one.`);
  process.exit(1);
}

writeFileSync('bases.js',
`/* Generated by bases.mjs from ${DIR}/ — do not edit, edit the JSON and re-run.
   ${out.length} templates, each one checked for duplicate ids, unresolved
   needs, cycles, missing palette colours, non-numeric costs and rootlessness
   before it got here. */
window.BASES = ${JSON.stringify(out, null, 1)};
`);

console.log(`\nbases.js · ${out.length} templates · ` +
  out.map((t) => `${t.id} (${t._stats.sectors})`).join(', '));
