#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   builds.mjs — compiles templates-build/*.json into builds.js.

   Buildings are data, the same way rosters are. A kind is a list of PARTS,
   each part gated by tier with `from` and `upto`, and the renderer only
   executes them. Adding a building is writing JSON; it is never writing code.

   THE +1 LAW IS CHECKED HERE, because it is the one rule the whole yard rests
   on and a rule nobody checks is a rule nobody has. Every kind must:

     · have exactly four tiers, so no kind can outgrow another
     · gain parts monotonically — a part may APPEAR at a tier, and the count
       may never fall as tier rises
     · never lose a tier's worth of structure to make room for the next

   That last one is what stops a "better" building existing. Tier 4 of the
   granary is not superior to tier 4 of the forge; both are four increments
   from where they started, and nothing in the data can express otherwise.
   A kind that shrank on promotion would be introducing a trade-off, and a
   trade-off is a ranking, and a ranking is where a syndicate attaches.

       node builds.mjs
   ═══════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'templates-build';
const SHAPES = new Set(['box', 'roof', 'cyl', 'cone', 'merlons', 'flag', 'row',
                        'grove', 'flock', 'fence', 'dog', 'seal']);
const files = readdirSync(DIR).filter(f => f.endsWith('.json')).sort();
const out = [];
let fatal = 0;

for (const f of files) {
  const t = JSON.parse(readFileSync(join(DIR, f), 'utf8'));
  const errs = [], parts = t.parts || [];

  if (!Array.isArray(t.tiers) || t.tiers.length !== 4)
    errs.push(`must name exactly 4 tiers, found ${(t.tiers || []).length}`);
  if (!Array.isArray(t.grow) || t.grow.length !== 4)
    errs.push('grow must have 4 entries');

  parts.forEach((p, i) => {
    if (!SHAPES.has(p.s)) errs.push(`part ${i}: unknown shape "${p.s}"`);
    if (!Array.isArray(p.at) || p.at.length !== 3) errs.push(`part ${i}: at must be [x,y,z]`);
    if (p.from !== undefined && (p.from < 1 || p.from > 4)) errs.push(`part ${i}: from out of range`);
    if (p.upto !== undefined && (p.upto < 1 || p.upto > 4)) errs.push(`part ${i}: upto out of range`);
    if (p.from !== undefined && p.upto !== undefined && p.from > p.upto)
      errs.push(`part ${i}: from ${p.from} is after upto ${p.upto}`);
  });

  /* the +1 check: part count may never fall as tier rises */
  const at = t => parts.filter(p => (p.from || 1) <= t && (p.upto || 4) >= t).length;
  const counts = [1, 2, 3, 4].map(at);
  for (let i = 1; i < 4; i++)
    if (counts[i] < counts[i - 1])
      errs.push(`+1 violated: tier ${i + 1} has ${counts[i]} parts, tier ${i} had ${counts[i - 1]}`);
  if (counts[3] === counts[0])
    errs.push('nothing is gained across four tiers — this kind does not grow');

  const tag = errs.length ? 'REFUSED' : 'ok';
  console.log(`${tag.padEnd(8)} ${f.padEnd(16)} ${String(parts.length).padStart(2)} parts · ` +
    `tiers ${counts.join(' → ')} · ${t.tiers.join(' → ')}`);
  errs.forEach(e => console.log(`         ✗ ${e}`));
  if (errs.length) { fatal++; continue; }

  t._counts = counts;
  out.push(t);
}

if (fatal) {
  console.log(`\n${fatal} refused. builds.js not written.`);
  process.exit(1);
}

writeFileSync('builds.js',
`/* Generated by builds.mjs from ${DIR}/ — do not edit, edit the JSON and re-run.
   ${out.length} building kinds, four tiers each, every one checked for the +1
   law: parts may appear as tier rises and may never fall away to pay for them.
   No kind can outgrow another, so no kind is worth more than another. */
window.BUILDS = ${JSON.stringify(Object.fromEntries(out.map(t => [t.id, t])))};
`);

const total = out.reduce((a, t) => a + t.parts.length, 0);
console.log(`\nbuilds.js · ${out.length} kinds · ${total} parts · all +1 monotone`);
