#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   challenges.mjs — compiles templates-challenge/*.json into challenges.js.

   The content layer. Coding problems, assessments, writing challenges,
   math-writing exercises, and the one layer that is crafted rather than
   generated: voice and perspective.

   WHAT IS CHECKED, AND WHY EACH CHECK EXISTS

   · NO POINTS ANYWHERE. A rubric is a list of bands, each with a test, and no
     band carries a number. The moment a band is worth 3 and another is worth
     1, there is a ranking, and a ranking is where a syndicate attaches. This
     is the +1 law applied to assessment: completing a challenge is one
     increment, and which challenge you completed is not comparable.

   · EVERY BAND IS A QUESTION. A band whose test is a description rather than
     something answerable yes or no is an opinion with a heading on it — the
     same rule kb.json holds its entries to.

   · VOICE CHALLENGES NEED SOURCES AND AT LEAST THREE STANDPOINTS. Fewer than
     three and it is a position rather than an exercise: two standpoints is a
     debate and a debate has a winner. Three or more forces the writer to
     inhabit somebody they did not choose.

   · `unlocks` MUST NAME A REAL KB ENTRY, checked against kb.json, so the
     content layer and the knowledge base cannot drift apart silently.

       node challenges.mjs
   ═══════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'templates-challenge';
const TYPES = new Set(['voice', 'code', 'write', 'math', 'assess']);
const kb = existsSync('kb.json')
  ? new Set(JSON.parse(readFileSync('kb.json', 'utf8')).entries.map(e => e.id))
  : null;

const files = readdirSync(DIR).filter(f => f.endsWith('.json')).sort();
const out = [];
let fatal = 0;

for (const f of files) {
  const c = JSON.parse(readFileSync(join(DIR, f), 'utf8'));
  const errs = [];

  if (!TYPES.has(c.type)) errs.push(`unknown type "${c.type}"`);
  if (!c.title) errs.push('no title');
  if (!c.ground) errs.push('no ground — a challenge with no situation is a prompt');
  if (!c.task) errs.push('no task');
  if (!Array.isArray(c.rubric) || c.rubric.length < 3)
    errs.push('rubric needs at least three bands');

  (c.rubric || []).forEach((b, i) => {
    if (!b.band || !b.test) errs.push(`rubric ${i}: needs a band and a test`);
    if ('points' in b || 'score' in b || 'weight' in b)
      errs.push(`rubric ${i}: carries a number — no band may be worth more than another`);
    /* a band must be ANSWERABLE — it must contain a question. It need not end
       with one: "Does it fail? Prove it by adding a unit." is a better band
       than the question alone, and an earlier version of this check refused it. */
    if (b.test && !b.test.includes('?'))
      errs.push(`rubric ${i}: test is not answerable ("${b.test.slice(0, 44)}…")`);
  });

  if (c.type === 'voice') {
    if (!Array.isArray(c.sources) || !c.sources.length)
      errs.push('a voice challenge with no sources is fiction wearing history');
    if (!Array.isArray(c.standpoints) || c.standpoints.length < 3)
      errs.push(`needs 3+ standpoints, has ${(c.standpoints || []).length} — two is a debate, and a debate has a winner`);
    (c.standpoints || []).forEach((s, i) => {
      if (!s.who || !s.brief) errs.push(`standpoint ${i}: needs who and brief`);
    });
  }

  if (c.unlocks && kb && !kb.has(c.unlocks))
    errs.push(`unlocks "${c.unlocks}", which is not an entry in kb.json`);

  const tag = errs.length ? 'REFUSED' : 'ok';
  console.log(`${tag.padEnd(8)} ${f.padEnd(22)} ${c.type.padEnd(6)} ` +
    `${(c.rubric || []).length} bands` +
    (c.standpoints ? ` · ${c.standpoints.length} standpoints` : '') +
    (c.unlocks ? ` · ${c.unlocks}` : ''));
  errs.forEach(e => console.log(`         ✗ ${e}`));
  if (errs.length) { fatal++; continue; }
  out.push(c);
}

if (fatal) {
  console.log(`\n${fatal} refused. challenges.js not written.`);
  process.exit(1);
}

writeFileSync('challenges.js',
`/* Generated by challenges.mjs from ${DIR}/ — do not edit, edit the JSON.
   ${out.length} challenges. No rubric band anywhere carries a number: completing
   one is +1, and which one you completed is not comparable to which one somebody
   else did. Every band is a question a reader can answer yes or no. Voice
   challenges carry sources and at least three standpoints, because two is a
   debate and a debate has a winner. */
window.CHALLENGES = ${JSON.stringify(out)};
`);

const by = {};
out.forEach(c => by[c.type] = (by[c.type] || 0) + 1);
const bands = out.reduce((a, c) => a + c.rubric.length, 0);
const stands = out.reduce((a, c) => a + (c.standpoints || []).length, 0);
console.log(`\nchallenges.js · ${out.length} challenges · ` +
  Object.entries(by).map(([k, v]) => `${v} ${k}`).join(', '));
console.log(`  ${bands} rubric bands, 0 of them scored · ${stands} standpoints`);
