#!/usr/bin/env node
/* descent.mjs — builds descent.html: the ground landing, paid in HEZE, gated by the lessons.

   The yard has a unit of account (heze.html: 21,000,000, fixed, not a token,
   not for sale) and a school (templates-lesson/*.json: six lessons with
   prerequisites, each with a practice you write in JavaScript and checks that
   mark it). This page joins them to the one goal the yard has always talked
   around: putting something on the ground at 475 °C and 92 bar, and keeping it
   alive longer than Venera 13's 127 minutes.

   Pass a lesson, the docket credits HEZE. Spend HEZE on the stages of the
   approach; each stage also asks for the lesson whose idea it needs. Land.
   Then stay: the surface clock pays HEZE per minute of data, the yard's
   hardening classes buy more minutes, and the clock is credited in full while
   you are away, which is what the last lesson teaches.

   Generated from the lesson files so the page cannot drift from the school.
       node descent.mjs
*/
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

const lessons = readdirSync('templates-lesson').filter(f => f.endsWith('.json'))
  .map(f => JSON.parse(readFileSync('templates-lesson/' + f, 'utf8')))
  .sort((a, b) => +a.order - +b.order);
const page = readFileSync('descent.page.js', 'utf8');
const checks = lessons.reduce((a, l) => a + l.practice.checks.length, 0);

const DEF = {
  cap: 21000000,
  perMinute: 100,
  grants: { 'b2p2p2b': 5000, 'fungibility-tokens': 8000, 'decentralized-coins': 12000, 'not-a-king': 20000, 'the-idle-board': 30000, 'graphics-engine': 10000 },
  stages: [
    { id: 'window',  name: 'The transfer window', heze: 1000,  km: null, needs: [], why: 'Every 584 days, and nothing you do hurries it. The yard\'s calendar is the synodic period.' },
    { id: 'capture', name: 'Capture and aerobrake', heze: 2100, km: 250, needs: ['graphics-engine'], why: 'Three numbers in, two numbers out. The trajectory is a projection you plot yourself, and the order you draw it in is the depth.' },
    { id: 'band',    name: 'The band, 50 km', heze: 3200, km: 50, needs: ['b2p2p2b'], why: 'Home. 1 bar, 60 °C, the aerostat. Hydrogen comes up the chain by ship or it does not come; if one party can stop it, it is not a chain.' },
    { id: 'probe',   name: 'The descent probe', heze: 12400, km: 10, needs: ['fungibility-tokens', 'decentralized-coins'], why: 'Spares that are interchangeable exactly because nothing remembers where they came from, and a probe that reads nothing on the way down because there is nothing to read.' },
    { id: 'ground',  name: 'Ground landing', heze: 28000, km: 0, needs: ['not-a-king'], why: '475 °C, 92 bar, about two hours. Nobody decides each case by radio. The rule was written before the case arrived, and now it runs.' },
  ],
  relanding: 12400, baseLife: 30, venera: 127,
  hardening: [
    { id: 'hull',   name: 'Pressure hull',              heze: 4600,   min: 20,   why: 'Bucketeer class. 92 bar is 910 metres of Earth ocean.' },
    { id: 'mass',   name: 'Thermal mass',               heze: 12400,  min: 40,   why: 'Destroyer class. Heat has to go somewhere; for a while it goes into the metal.' },
    { id: 'pcm',    name: 'Phase-change cooling',       heze: 28000,  min: 90,   why: 'Cruiser class. Lithium nitrate melts and takes the heat with it.' },
    { id: 'coat',   name: 'Sulphuric acid coat',        heze: 47000,  min: 120,  why: 'Monitor class. The clouds are acid; the surface is only hot.' },
    { id: 'sic',    name: 'Silicon-carbide electronics', heze: 61000, min: 240,  why: 'Carrier class. Chips that work at 500 °C exist; they are small and slow and enough.' },
    { id: 'rtg',    name: 'RTG and a Stirling cooler',  heze: 84000,  min: 600,  why: 'Battleship class. Power for the cooler that keeps the rest alive.' },
    { id: 'yamato', name: 'The refrigerator that will not fly', heze: 150000, min: 2000, why: 'Yamato class. 72,800 t. It holds.' },
  ],
  hardNeeds: 'the-idle-board',
};

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const html = `<title>The ground landing &middot; a Venus approach, paid in HEZE</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!--
  THE GROUND LANDING — the school, the docket, and the surface.

  Generated by descent.mjs from templates-lesson/ (${lessons.length} lessons, ${checks} checks) and the
  figures in heze.html and terraform.html. Pass a lesson and the docket credits
  HEZE. Spend HEZE on the approach: window, capture, the band, the probe, the
  ground. Each stage also asks for the lesson whose idea it needs. On the
  ground the clock pays HEZE per minute of data, hardening buys minutes, and
  the clock is credited in full while you are away.

  HEZE HERE IS ARITHMETIC in this browser's localStorage, exactly as heze.html
  slide six says: no token, no chain, nothing to buy or sell, and the 21,000,000
  cap is enforced by this page refusing to credit past it. It is not in the
  wallet and it will not be.

  SCRIPT: yes, and marked. The lessons are marked by running your code against
  their checks, which no stylesheet can do.
-->
<style>
  :root{--void:#0b0d12;--panel:#151922;--panel2:#1c2230;--edge:#2b3445;--ink:#efe9dc;--dim:#95a0b3;--gold:#f2c98a;--venus:#f0a83c;--ok:#6fd4a8;--bad:#e06f5a;--tide:#3f8fbf}
  *{box-sizing:border-box}
  html,body{margin:0;background:var(--void);color:var(--ink);font:14px/1.5 ui-rounded,system-ui,-apple-system,sans-serif}
  header{padding:14px 16px 6px;display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}
  header h1{margin:0;font-size:20px;color:var(--gold);font-weight:600}
  header small{color:var(--dim)}
  #sky{display:block;width:100%;height:190px;background:#0a0d16}
  main{padding:10px 14px 30px;max-width:1100px;margin:0 auto;display:grid;gap:12px}
  .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:6px}
  .stat{background:var(--panel);border:1px solid var(--edge);border-radius:10px;padding:8px 10px}
  .stat b{display:block;font-size:11px;color:var(--dim);font-weight:500;text-transform:uppercase;letter-spacing:.06em}
  .stat span{font-size:18px;font-variant-numeric:tabular-nums}
  .stat i{font-style:normal;color:var(--dim);font-size:11px;display:block}
  .cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}
  @media (max-width:820px){.cols{grid-template-columns:1fr}}
  section{background:var(--panel);border:1px solid var(--edge);border-radius:12px;padding:12px}
  section h2{margin:0 0 6px;font-size:12px;color:var(--dim);text-transform:uppercase;letter-spacing:.08em;font-weight:600}
  section h2 i{font-style:normal;text-transform:none;letter-spacing:0;font-weight:400;margin-left:6px}
  .card{background:var(--panel2);border:1px solid var(--edge);border-radius:10px;padding:10px;margin:6px 0;display:flex;flex-direction:column;gap:4px}
  .card.done{border-color:var(--ok)}.card.locked{opacity:.6}
  .card h3{margin:0;font-size:14px;font-weight:600;display:flex;justify-content:space-between;gap:8px}
  .card h3 span{color:var(--gold);font-variant-numeric:tabular-nums;white-space:nowrap}
  .card p{margin:0;color:var(--dim);font-size:12.5px}
  .card p.why{color:var(--ink);opacity:.85}
  button{font:inherit;color:var(--ink);background:var(--panel2);border:1px solid var(--edge);border-radius:9px;padding:7px 12px;cursor:pointer}
  button:hover:not(:disabled){border-color:var(--gold)}button:disabled{opacity:.45;cursor:not-allowed}
  button.primary{background:#2a2036;border-color:var(--venus)}
  .row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
  .badge{display:inline-block;background:var(--panel);border:1px solid var(--edge);border-radius:999px;padding:1px 8px;font-size:11px;color:var(--dim)}
  .badge.ok{border-color:var(--ok);color:var(--ok)}.badge.hot{border-color:var(--venus);color:var(--venus)}
  details{margin-top:4px}summary{cursor:pointer;color:var(--tide)}
  .lesson .sec{margin:8px 0}.lesson .sec h4{margin:0 0 2px;font-size:13px}.lesson .sec p{margin:0 0 4px;color:var(--dim);font-size:12.5px}
  textarea{width:100%;min-height:220px;font:12px/1.4 ui-monospace,Consolas,monospace;background:#0e1118;color:var(--ink);border:1px solid var(--edge);border-radius:8px;padding:8px;resize:vertical;tab-size:2}
  .checks{list-style:none;margin:6px 0;padding:0;font-size:12.5px}.checks li{padding:2px 0}.checks li.ok::before{content:"✓ ";color:var(--ok)}.checks li.bad::before{content:"✗ ";color:var(--bad)}.checks li.c{color:var(--dim)}
  .ledger{font:12px ui-monospace,Consolas,monospace;color:var(--dim);max-height:200px;overflow:auto}
  .ledger div{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid var(--edge);padding:2px 0}
  .ledger b{color:var(--gold);font-weight:500}
  footer{padding:10px 16px 24px;color:var(--dim);font-size:12px;max-width:1100px;margin:0 auto}
  footer a{color:var(--tide);text-decoration:none}
</style>
<header><h1>The ground landing</h1><small>a Venus approach, paid in HEZE, gated by the school</small><span style="flex:1"></span><small id="clock"></small></header>
<canvas id="sky" width="1100" height="190"></canvas>
<main>
  <div class="stats" id="stats"></div>
  <div class="cols">
    <div>
      <section id="approach"><h2>The approach<i>five stages, in the order they have to happen in</i></h2><div id="stages"></div></section>
      <section id="surface"><h2>The surface<i>475 °C · 92 bar · the record to beat is ${DEF.venera} minutes</i></h2><div id="lander"></div><div id="hardening"></div></section>
      <section><h2>The docket<i>HEZE is a unit of account in these files. Not money, not a token, not the wallet.</i></h2><div class="ledger" id="ledger"></div>
        <div class="row" style="margin-top:8px"><button id="export">Download the docket (JSON)</button><button id="wipe">Start again</button></div></section>
    </div>
    <div>
      <section id="school"><h2>The school<i>${lessons.length} lessons; each pays the docket once, when its checks pass</i></h2><div id="lessons"></div></section>
    </div>
  </div>
</main>
<footer>Figures: 475 °C and 92 bar from <a href="terraform.html">terraform.html</a>; 584 days from <a href="game.html">the game</a>; the price ladder from <a href="heze.html">heze.html</a>; the lessons from <a href="school.html">the school</a>. Nothing here is money. <a href="arcade.html">← the arcade</a> · <a href="index.html">the yard</a></footer>
<script id="lessons-json" type="application/json">${JSON.stringify(lessons).replace(/<\//g, '<\\/')}</script>
<script id="def-json" type="application/json">${JSON.stringify(DEF)}</script>
<script>
${page}
</script>
`;
writeFileSync('descent.html', html);
console.log(`wrote descent.html · ${lessons.length} lessons · ${checks} checks · ${DEF.stages.length} stages · ${DEF.hardening.length} hardenings · ${html.length} bytes`);
