#!/usr/bin/env node
/* digest.mjs — every interface, digested into the template of enums and sealed.

   For each interface in the yard, read what it has on disk (its templates,
   its rules, its ledger) and, if a saved state is handed in, what it is
   doing, and write a digest in the words of digest-enums.json and no others.
   A value the enums do not have becomes 'other' and is listed under 'stray',
   so the template grows by being edited, not by being guessed at. Then seal
   the digest with the interface's own name as the words, onto the shelf that
   dispatch.html reads, where it is decoded into chips.

     node digest.mjs all              digest and seal every interface
     node digest.mjs <name> [state.json]
     node digest.mjs show <name>      print the digest, unsealed, to check the template */
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { seal } from './dispatch.mjs';

const ENUMS = JSON.parse(readFileSync('digest-enums.json', 'utf8'));
const stray = []; const E = (field, value) => { const list = ENUMS[field] || []; if (list.includes(value)) return value; stray.push(`${field}: ${value}`); return 'other'; };
const count = d => existsSync(d) ? readdirSync(d).filter(f => f.endsWith('.json') && !f.startsWith('_')).length : 0;
const size = n => n === 0 ? 'nothing yet' : n < 10 ? 'tiny' : n < 50 ? 'small' : n < 200 ? 'middling' : n < 1000 ? 'large' : 'vast';
const json = p => existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null;

const DIGESTERS = {
  grass: st => { const d = json('grass/def.json'); return { kind: E('kind', 'idle game'), mood: E('mood', st && st.res ? (st.res.grass > 1e6 ? 'thriving' : st.res.grass > 1000 ? 'growing' : 'quiet') : 'quiet'), size: E('size', size(d.machines.length + d.sectors.length + d.research.length)), money: E('money', 'not money'), time: E('time', st && st.ring > 1 ? 'a ring' : 'days'), guest: E('guest', st && st.playstyle ? ({ dragon: 'the dragon', viking: 'the longship crew', fae: 'the fae', egyptian: 'the house of Ma\'at' })[st.playstyle] || st.playstyle : 'none'), shape: E('shape', st && st.form != null ? (d.becoming.forms[st.form] || {}).shape || 'blade' : 'blade'), eyes: E('eyes', 'none drawn'), numbers: { things: d.machines.length, chapters: d.sectors.length, sayings: d.research.length, templates: count('grass/templates') } }; },
  wallet: () => ({ kind: E('kind', 'wallet'), mood: E('mood', 'sealed'), size: E('size', 'small'), money: E('money', 'none'), time: E('time', 'forever'), custody: E('custody', 'one key'), eyes: E('eyes', 'none drawn'), numbers: { families: 3, chains: 29 } }),
  descent: st => ({ kind: E('kind', 'school'), mood: E('mood', st && st.lander && st.lander.alive ? 'held' : st && st.stages && st.stages.includes('ground') ? 'fallen' : 'quiet'), size: E('size', size(count('templates-lesson') * 10)), money: E('money', st && st.heze > 1e6 ? 'a fortune' : st && st.heze > 1e4 ? 'plenty' : st && st.heze > 0 ? 'some' : 'none'), time: E('time', 'days'), eyes: E('eyes', 'none drawn'), numbers: { lessons: count('templates-lesson'), stages: 5, hardenings: 7 } }),
  ledger: st => { const ok = existsSync('ledger/bank/ledger.jsonl'); return { kind: E('kind', 'ledger'), mood: E('mood', ok ? 'quiet' : 'nothing yet'), size: E('size', size(ok ? readFileSync('ledger/bank/ledger.jsonl', 'utf8').split('\n').filter(Boolean).length : 0)), money: E('money', 'not money'), time: E('time', 'two centuries'), custody: E('custody', 'two of three'), verdict: E('verdict', 'verified'), ends: E('ends', 'both plural'), health: E('health', 'no credential'), eyes: E('eyes', 'none drawn'), numbers: { tranches: 21, cap: 21000000, years: 200, tests: 9 } }; },
  troy: st => ({ kind: E('kind', 'war'), mood: E('mood', st && st.fallen === 'troy' ? 'fallen' : st && st.fallen === 'helen' ? 'returned' : st && st.day > 0 ? 'besieged' : 'quiet'), size: E('size', 'small'), money: E('money', 'not money'), time: E('time', 'a decade'), eyes: E('eyes', 'none drawn'), numbers: { hulls: 9, heroes: 7, routes: 6, council: 7 } }),
  siege: st => ({ kind: E('kind', 'tower defence'), mood: E('mood', st && st.over === 'held' ? 'held' : st && st.over ? 'fallen' : st && st.wave > 0 ? 'besieged' : 'quiet'), size: E('size', size(count('templates-prince') * 5)), money: E('money', 'not money'), time: E('time', 'a decade'), eyes: E('eyes', 'none drawn'), numbers: { princes: count('templates-prince'), shapes: count('templates-demon'), spells: count('templates-spell'), ahead: 7 } }),
  tribunal: () => ({ kind: E('kind', 'tribunal'), mood: E('mood', 'quiet'), size: E('size', size(count('templates-act') + count('templates-act-fleet'))), money: E('money', 'none'), time: E('time', 'a decade'), verdict: E('verdict', 'discretion'), king: E('king', 'Agamemnon'), eyes: E('eyes', 'none drawn'), numbers: { acts: count('templates-act') + count('templates-act-fleet'), votes: count('templates-vote') + count('templates-vote-fleet'), verdicts: count('templates-verdict') + count('templates-verdict-fleet'), causes: 2 } }),
  farm: st => ({ kind: E('kind', 'farm'), mood: E('mood', st && st.harvested > 0 ? 'growing' : 'quiet'), size: E('size', size(count('templates-farm'))), money: E('money', 'not money'), time: E('time', 'a season'), season: E('season', st && st.season != null ? ['thaw', 'sowing', 'the long days', 'first cut', 'harvest', 'the fallow', 'frost', 'deep winter'][st.season % 8] : 'thaw'), weather: E('weather', st && st.weather ? st.weather.id.replace(/^weather-\d+$/, 'fair') : 'fair'), chain: E('chain', 'four deep'), eyes: E('eyes', 'none drawn'), numbers: { looms: 10, patterns: 25, moulds: 50, leaves: count('templates-farm') } }),
  village: st => ({ kind: E('kind', 'settlement'), mood: E('mood', st && st.households > 10 ? 'thriving' : st && st.households > 0 ? 'growing' : 'quiet'), size: E('size', size(count('templates-village'))), money: E('money', 'not money'), time: E('time', 'a season'), chain: E('chain', 'five deep'), eyes: E('eyes', 'none drawn'), numbers: { templates: count('templates-village'), households: st ? st.households || 0 : 0 } }),
  town: st => ({ kind: E('kind', 'settlement'), mood: E('mood', st && st.chartered ? 'thriving' : st && st.citizens > 0 ? 'growing' : 'quiet'), size: E('size', size(count('templates-town'))), money: E('money', 'not money'), time: E('time', 'a year'), chain: E('chain', 'six deep'), eyes: E('eyes', 'none drawn'), numbers: { templates: count('templates-town'), citizens: st ? st.citizens || 0 : 0 } }),
  clans: st => ({ kind: E('kind', 'portfolio'), mood: E('mood', st && st.raidsTaken > st.raidsBroken ? 'besieged' : st && st.held && st.held.length ? 'growing' : 'quiet'), size: E('size', size(count('templates-asset'))), money: E('money', 'not money'), time: E('time', 'days'), chain: E('chain', 'two deep'), eyes: E('eyes', 'none drawn'), numbers: { assets: count('templates-asset'), clans: count('templates-clan'), periods: [2, 3, 5, 7, 11, 13] } }),
  market: st => ({ kind: E('kind', 'market'), mood: E('mood', st && st.held && st.held.length ? 'growing' : 'quiet'), size: E('size', size(4 * 4 ** (st ? st.degree || 3 : 3))), money: E('money', 'not money'), time: E('time', 'days'), chain: E('chain', 'two deep'), eyes: E('eyes', 'none drawn'), numbers: { onDisk: count('templates-ticker'), ninth: 4 * 4 ** 9, visualFrom: 5 } }),
  continent: st => { const grown = st && st.cells ? st.cells.filter(c => c === 2).length : 0; return { kind: E('kind', 'continent'), mood: E('mood', grown > 2000 ? 'thriving' : grown > 0 ? 'growing' : 'quiet'), size: E('size', size(count('templates-continent'))), money: E('money', 'not money'), time: E('time', 'days'), chain: E('chain', 'seven deep'), eyes: E('eyes', 'none drawn'), numbers: { parcels: count('templates-continent') - 6, regions: 6, grown } }; },
  coven: st => ({ kind: E('kind', 'coven'), mood: E('mood', st && (st.chain || []).length ? 'growing' : 'quiet'), size: E('size', size(count('templates-coven'))), money: E('money', 'not money'), time: E('time', 'two centuries'), custody: E('custody', 'two of three'), chain: E('chain', 'two deep'), eyes: E('eyes', 'none drawn'), numbers: { practitioners: 63, syndicates: 21, doors: 200, checkpoints: st ? (st.chain || []).length : 0, crofts: count('templates-croft'), holdTypes: count('templates-hold'), holdsBuilt: st ? Object.values(st.built || {}).reduce((a, b) => a + b.length, 0) : 0, activityStates: count('templates-activity') } }),
  glossary: st => ({ kind: E('kind', 'glossary'), mood: E('mood', st && (st.lines || []).length > 20 ? 'thriving' : 'quiet'), size: E('size', 'large'), money: E('money', 'none'), time: E('time', 'forever'), eyes: E('eyes', 'none drawn'), numbers: { terms: 216, lines: st ? (st.lines || []).length : 0 } }),
  terminal: st => ({ kind: E('kind', 'terminal'), mood: E('mood', st && (st.hist || []).length ? 'growing' : 'quiet'), size: E('size', 'small'), money: E('money', 'not money'), time: E('time', 'forever'), eyes: E('eyes', 'none drawn'), numbers: { commands: 20, definitions: 118, macros: st ? Object.keys(st.macros || {}).length : 0 } }),
  dispatch: () => ({ kind: E('kind', 'shelf'), mood: E('mood', 'sealed'), size: E('size', size(existsSync('dispatches.jsonl') ? readFileSync('dispatches.jsonl', 'utf8').split('\n').filter(Boolean).length : 0)), money: E('money', 'none'), time: E('time', 'forever'), eyes: E('eyes', 'none drawn'), numbers: { rounds: 200000 } }),
};
export function digest(name, state) { stray.length = 0; const f = DIGESTERS[name]; if (!f) throw new Error('no such interface'); const body = f(state); return { digest: true, interface: E('interface', name), cute: E('cute', 'very'), ...body, stray: [...stray], enums: Object.keys(ENUMS).filter(k => k !== 'note') }; }

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) {
  const [, , cmd, a, b] = process.argv;
  if (cmd === 'all') { for (const n of Object.keys(DIGESTERS)) { const d = digest(n, null); const s = seal(n, `Digest: ${n}`, JSON.stringify(d), ['digest', n]); console.log(`${s.id} ${n}: ${d.kind} · ${d.mood} · ${d.size}${d.stray.length ? ' · stray: ' + d.stray.join(', ') : ''}`); } }
  else if (cmd === 'show') console.log(JSON.stringify(digest(a, b ? json(b) : null), null, 1));
  else if (DIGESTERS[cmd]) { const d = digest(cmd, a ? json(a) : null); const s = seal(cmd, `Digest: ${cmd}`, JSON.stringify(d), ['digest', cmd]); console.log(`${s.id} sealed with the word "${cmd}"`); }
  else console.log('all | show <name> [state.json] | <name> [state.json]');
}
