#!/usr/bin/env node
/* entities.mjs — one Scala class per template family, and nothing borrowed to write it.

   enums.mjs solidified the vocabulary; this solidifies the shape. For every
   templates- family, sample its files, work out the type of every field —
   including one nested inside an object, or repeated inside an array, down
   three levels deep — and write ONE Scala source file that models the whole
   body: a case class for the template, a case class for every nested object
   and array-of-object it contains, and a real Scala 3 enum, backed by the
   raw string, for every field whose vocabulary is closed rather than free
   text. Each file also carries a fromMap constructor, so a template can be
   rebuilt exactly from its own decoded fields with nothing but that one
   class and the family's own file — nothing imported from another family's
   generated code, nothing hand-maintained. Scala is the production language
   for Venus; this is the yard's own copy of that boundary, regenerated by
   running this script again whenever the templates it reads change shape.

     node entities.mjs         write venus-core/src/main/scala/io/cityoflight/virgo/scala/templates/*.scala */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
/* This repo is rooted one level above Venus/ (see CLAUDE.md's repo structure notes), and that is
   where venus-core/ — the real Scala production tree — lives too, as a sibling of Venus/, not
   nested inside it. root here is Venus/ itself, so the Scala output has to climb out one level. */
const OUT = join(root, '..', 'venus-core/src/main/scala/io/cityoflight/virgo/scala/templates');
mkdirSync(OUT, { recursive: true });

const SAMPLE = 60;        // files sampled per family to infer shape — structure repeats fast, this is plenty
const ENUM_CAP = 30;      // a string field with more distinct values than this stays a plain String
const PROSE_LEN = 40;     // a field averaging longer than this, in characters, is prose, not a category
const UNIQUE_RATIO = 0.8; // a field this close to a different value in every sample is an id, not an enum

const RESERVED = new Set(['type', 'yield', 'object', 'class', 'def', 'val', 'var', 'if', 'else', 'for', 'while',
  'do', 'try', 'catch', 'finally', 'new', 'super', 'this', 'null', 'true', 'false', 'import', 'package', 'trait',
  'extends', 'with', 'override', 'abstract', 'final', 'sealed', 'implicit', 'lazy', 'private', 'protected',
  'return', 'throw', 'enum', 'given', 'using', 'match', 'case', 'forSome', 'macro']);
const ident = s => RESERVED.has(s) ? '`' + s + '`' : s;

function pascal(s) {
  const w = String(s).replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(/\s+/).filter(Boolean);
  return w.map(x => x[0].toUpperCase() + x.slice(1)).join('') || 'X';
}
const BLOCK_IDENT = new Set(['None', 'Some', 'Any', 'Unit', 'Boolean', 'Int', 'Long', 'Double', 'String', 'Nothing', 'Null', 'Option', 'List', 'Map']);
function caseNamer() {
  const used = new Set();
  return raw => {
    let n = pascal(raw); if (/^[0-9]/.test(n)) n = 'V' + n; if (BLOCK_IDENT.has(n)) n += '_';
    let base = n, i = 2; while (used.has(n)) n = base + i++;
    used.add(n); return n;
  };
}

function buildShape(values, depth) {
  const nonNull = values.filter(v => v !== null && v !== undefined);
  if (!nonNull.length) return { kind: 'unknown' };
  const kinds = new Set(nonNull.map(v => Array.isArray(v) ? 'array' : typeof v === 'object' ? 'object' : typeof v));
  if (kinds.size !== 1) return { kind: 'unknown' };
  const [kind] = kinds;
  if (kind === 'object') {
    const names = new Set(); for (const o of nonNull) for (const k of Object.keys(o)) names.add(k);
    const fields = {};
    for (const k of names) fields[k] = depth < 3 ? buildShape(nonNull.map(o => o[k]).filter(v => v !== undefined), depth + 1) : { kind: 'unknown' };
    return { kind: 'object', fields };
  }
  if (kind === 'array') { const elems = []; for (const a of nonNull) for (const e of a) elems.push(e); return { kind: 'array', of: buildShape(elems, depth + 1) }; }
  if (kind === 'string') {
    const counts = new Map(); for (const v of nonNull) counts.set(v, (counts.get(v) || 0) + 1);
    const distinct = counts.size, avgLen = nonNull.reduce((a, s) => a + s.length, 0) / nonNull.length;
    const tooUnique = nonNull.length >= 5 && distinct / nonNull.length > UNIQUE_RATIO;
    return distinct <= ENUM_CAP && avgLen <= PROSE_LEN && !tooUnique ? { kind: 'enum', values: [...counts.keys()].sort() } : { kind: 'string' };
  }
  if (kind === 'number') return { kind: nonNull.every(Number.isInteger) ? 'int' : 'double' };
  if (kind === 'boolean') return { kind: 'bool' };
  return { kind: 'unknown' };
}

function renderEnum(typeName, values) {
  const name = caseNamer();
  const cases = values.map(v => ({ name: name(v), raw: v }));
  return { enumTypeName: typeName, text:
`enum ${typeName}(val raw: String) {
${cases.map(c => `  case ${c.name} extends ${typeName}(${JSON.stringify(c.raw)})`).join('\n')}
}
object ${typeName} {
  def fromRaw(s: String): ${typeName} = values.find(_.raw == s).getOrElse(throw new IllegalArgumentException("unknown ${typeName}: " + s))
}` };
}

function exprFor(type, expr, enumNames) {
  if (type === 'String') return `${expr}.toString`;
  if (type === 'Int') return `${expr}.toString.toDouble.toInt`;
  if (type === 'Double') return `${expr}.toString.toDouble`;
  if (type === 'Boolean') return `${expr}.asInstanceOf[Boolean]`;
  if (type.startsWith('List[')) return `${expr}.asInstanceOf[List[Any]].map(x => ${exprFor(type.slice(5, -1), 'x', enumNames)})`;
  if (enumNames.has(type)) return `${type}.fromRaw(${expr}.toString)`;
  return `${type}.fromMap(${expr}.asInstanceOf[Map[String, Any]])`;
}

function renderClass(typeName, fields, enumNames) {
  const params = fields.map(f => `${ident(f.name)}: ${f.type}`).join(', ');
  const args = fields.map(f => `    ${ident(f.name)} = ${exprFor(f.type, `m(${JSON.stringify(f.name)})`, enumNames)}`).join(',\n');
  return `case class ${typeName}(${params})
object ${typeName} {
  def fromMap(m: Map[String, Any]): ${typeName} = ${typeName}(
${args}
  )
}`;
}

function generate(family) {
  const dir = join(root, family), short = family.replace(/^templates-/, '');
  const all = readdirSync(dir).filter(f => f.endsWith('.json') && !f.startsWith('_'));
  if (!all.length) return null;
  const step = all.length > SAMPLE ? Math.ceil(all.length / SAMPLE) : 1;
  const sample = all.filter((_, i) => i % step === 0);
  const bodies = []; for (const f of sample) { try { bodies.push(JSON.parse(readFileSync(join(dir, f), 'utf8'))); } catch { } }
  const shape = buildShape(bodies, 0);
  if (shape.kind !== 'object') return null;

  const fam = pascal(short), decls = [], enumNames = new Set();
  const typeNameFor = tokens => fam + tokens.map(t => t === '[]' ? 'Item' : pascal(t)).join('');

  function typeOf(node, tokens) {
    switch (node.kind) {
      case 'string': case 'unknown': return 'String';
      case 'int': return 'Int';
      case 'double': return 'Double';
      case 'bool': return 'Boolean';
      case 'enum': { const t = typeNameFor(tokens); enumNames.add(t); decls.push(renderEnum(t, node.values).text); return t; }
      case 'array': return `List[${typeOf(node.of, [...tokens, '[]'])}]`;
      case 'object': {
        const t = typeNameFor(tokens);
        const fields = Object.entries(node.fields).map(([k, v]) => ({ name: k, type: typeOf(v, [...tokens, k]) }));
        decls.push(renderClass(t, fields, enumNames));
        return t;
      }
    }
  }
  const topFields = Object.entries(shape.fields).map(([k, v]) => ({ name: k, type: typeOf(v, [k]) }));
  const topName = fam + 'Template';
  const header = `/** The whole body of one JSON template from ${family}, in one class. Auto-generated by
  * entities.mjs from ${sample.length} of its ${all.length} templates — regenerate rather than hand-edit.
  * ${topName}.fromMap(m) rebuilds an instance exactly from its own decoded fields. */
`;
  decls.push(header + renderClass(topName, topFields, enumNames));
  return { short, text: decls.join('\n\n') };
}

const families = readdirSync(root, { withFileTypes: true })
  .filter(e => e.isDirectory() && e.name.startsWith('templates-')).map(e => e.name).sort();

let written = 0, classCount = 0, enumCount = 0;
for (const family of families) {
  const g = generate(family);
  if (!g) continue;
  const body = `package io.cityoflight.virgo.scala.templates

${g.text}
`;
  writeFileSync(join(OUT, `${pascal(g.short)}Template.scala`), body);
  written++;
  classCount += (body.match(/^case class /gm) || []).length;
  enumCount += (body.match(/^enum /gm) || []).length;
}
console.log(`${written} families → venus-core/src/main/scala/io/cityoflight/virgo/scala/templates/: ${classCount} case classes, ${enumCount} enums`);
