#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   factions.mjs — compiles templates-faction/*.json into factions.js.

   THE LAYER ABOVE THE GUILD, AND A DIFFERENT SHAPE ENTIRELY.

   A guild is a bank to an amateur and an amateur farm to a journeyman: both
   positions profit, which is why it is stable and why it extracts. A FACTION
   is neither of those. It is a patron. It bears the whole expense of somebody
   whose OUTPUT IS THE EXPENSE — not funding a thing in order to sell it, but
   paying for a thing to exist, because some things should be done.

   THE DEFINING FEATURE IS WHAT IT MAY NOT HAVE, and that is what this file
   checks. No milestones. No deliverables. No review, no clawback, no renewal
   conditions, no KPI, no performance gate.

   The reason is one line long: the moment a stream is conditional it is
   leverage. Leverage is a discretion. A discretion is where a syndicate
   attaches — every entry in this base that traces extraction traces it back
   to somebody having a choice about somebody else's income. An unconditional
   stream cannot be used to make anybody do anything, and that is not a
   side-effect of patronage, it is the whole of it.

   SO THE VALIDATOR REFUSES:

     · any field that creates a review, by name
     · `unconditional` set to anything but true
     · an `ends_when` that is a condition rather than a date or "never" —
       because a stream that ends "when it stops being productive" is a
       review wearing a clock
     · a `because` that promises a return, which is the same instrument in
       prose: a justification by future yield is a milestone nobody wrote down

   And it requires a `study` field, because "nice to have around and be
   studied" is the actual proposition and a faction that cannot say what is
   learnable from its existence is a subsidy rather than a patronage.

       node factions.mjs
   ═══════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'templates-faction';

/* fields that create a discretion. Named, so the refusal is specific. */
const GATES = ['milestones', 'milestone', 'deliverables', 'deliverable', 'review',
               'reviews', 'clawback', 'kpi', 'kpis', 'targets', 'quota',
               'performance', 'renewal_conditions', 'conditions', 'approval',
               'oversight', 'audit_gate'];

/* prose that promises a return is a milestone nobody wrote down */
const PROMISE = /\b(will (?:deliver|produce|yield|return|generate|pay)|in exchange for|so that (?:we|the yard) (?:can|may) (?:sell|profit|recover)|return on)\b/i;

const files = readdirSync(DIR).filter((f) => f.endsWith('.json')).sort();
const out = [];
let fatal = 0;

for (const f of files) {
  const c = JSON.parse(readFileSync(join(DIR, f), 'utf8'));
  const errs = [];

  for (const k of ['id', 'name', 'patron', 'holds', 'because', 'study', 'stream', 'ends_when'])
    if (!c[k]) errs.push(`missing ${k}`);

  /* the gates */
  for (const g of GATES)
    if (g in c) errs.push(`carries "${g}" — a conditional stream is leverage`);

  if (c.unconditional !== true)
    errs.push('`unconditional` must be true — that is what makes it a patronage');

  /* the term may be a date or perpetual, never a condition */
  if (c.ends_when && !/^(never|\d{4}(-\d{2}){0,2})$/.test(String(c.ends_when).trim()))
    errs.push(`ends_when "${c.ends_when}" is a condition — use a date or "never", ` +
              'because a stream that ends when somebody decides it should is a review');

  /* the justification may not be a promise */
  if (c.because && PROMISE.test(c.because))
    errs.push('`because` promises a return — that is a milestone written as prose');

  if (c.stream && typeof c.stream === 'object') {
    if (!c.stream.term) errs.push('stream needs a term');
    else if (!/^(perpetual|\d{4}(-\d{2}){0,2})$/.test(String(c.stream.term).trim()))
      errs.push(`stream.term "${c.stream.term}" is a condition, not a term`);
  }

  const tag = errs.length ? 'REFUSED' : 'ok';
  console.log(`${tag.padEnd(8)} ${(c.id || f).padEnd(18)} ` +
    `${c.unconditional === true ? 'unconditional' : 'CONDITIONAL '} · ` +
    `ends ${c.ends_when || '?'} · ${(c.produces_mostly || '—')}`);
  errs.forEach((e) => console.log(`         ✗ ${e}`));
  if (errs.length) { fatal++; continue; }
  out.push(c);
}

if (fatal) {
  console.log(`\n${fatal} refused. factions.js not written — a patronage with a ` +
    `gate in it is a guild that has not admitted what it is.`);
  process.exit(1);
}

writeFileSync('factions.js',
`/* Generated by factions.mjs from ${DIR}/ — do not edit, edit the JSON.
   ${out.length} factions. Every one is unconditional: no milestones, no
   deliverables, no review, no clawback, no renewal conditions, and no term
   that ends on somebody's judgement. A conditional stream is leverage,
   leverage is a discretion, and a discretion is where a syndicate attaches.
   Each one also carries a study field naming what is learnable from the thing
   existing, because a faction that cannot say that is a subsidy rather than
   a patronage. */
window.FACTIONS = ${JSON.stringify(out)};
`);

console.log(`\nfactions.js · ${out.length} factions · all unconditional · ` +
  `all perpetual`);
console.log(`  what they mostly produce: ${out.map((c) => c.produces_mostly).join(' · ')}`);
