/* farm.page.js — the script for farm.html. Inlined by loom.mjs at build; not loaded on its own. */
(function () {
  const D = JSON.parse(document.getElementById('def-json').textContent);
  const $ = s => document.querySelector(s), el = (t, a = {}, ...k) => { const e = document.createElement(t); for (const [n, v] of Object.entries(a)) { if (v == null) continue; n === 'html' ? e.innerHTML = v : n.startsWith('on') ? e[n] = v : e.setAttribute(n, v); } k.forEach(x => e.append(x)); return e; };
  const fmt = n => Math.round(n).toLocaleString('en-US');
  const CAP = 21000000, DKEY = 'descent.v1', KEY = 'farm.v1';
  let Dk; try { Dk = Object.assign({ heze: 0, issued: 0, ledger: [] }, JSON.parse(localStorage.getItem(DKEY) || 'null') || {}); } catch (e) { Dk = { heze: 0, issued: 0, ledger: [] }; }
  const saveD = () => { Dk.saved = Date.now(); localStorage.setItem(DKEY, JSON.stringify(Dk)); };
  const credit = (amt, line) => { const a = Math.min(amt, Math.max(0, CAP - Dk.issued)); if (a <= 0) return 0; Dk.heze += a; Dk.issued += a; Dk.ledger.unshift({ t: Date.now(), line: 'Farm: ' + line, amt: a }); Dk.ledger.length = Math.min(Dk.ledger.length, 300); return a; };
  const debit = (amt, line) => { if (Dk.heze < amt) return false; Dk.heze -= amt; Dk.ledger.unshift({ t: Date.now(), line: 'Farm: ' + line, amt: -amt }); return true; };
  const fresh = () => ({ day: 0, fields: {}, tools: [], beasts: [], waters: [], fences: [], stores: [], markets: [], water: 100, store: 0, weather: null, season: 0, seasonLeft: D.seasons[0].length, harvested: 0, sold: 0, grant: false, log: [], saved: Date.now() });
  let S = fresh(); try { S = Object.assign(fresh(), JSON.parse(localStorage.getItem(KEY) || 'null') || {}); } catch (e) {}
  const note = m => { S.log.unshift({ t: Math.floor(S.day), m }); S.log.length = Math.min(S.log.length, 50); };
  const save = () => { S.saved = Date.now(); localStorage.setItem(KEY, JSON.stringify(S)); saveD(); };
  if (!S.grant) { S.grant = true; credit(6000, 'the first spring: seed money against the cap'); note('The land is bare. Six thousand HEZE for seed, against the cap; the rest the fields will have to earn.'); }
  const leaf = (kind, id) => D[kind].find(x => x.id === id);
  const season = () => D.seasons[S.season % D.seasons.length];
  const waterCap = () => 100 + S.waters.reduce((a, id) => a + leaf('waters', id).holds, 0);
  const storeCap = () => S.stores.reduce((a, id) => a + leaf('stores', id).holds, 0);

  function step(dt, quiet) { S.day += dt; S.seasonLeft -= dt; if (S.seasonLeft <= 0) { S.season++; S.seasonLeft = season().length; note(`${season().turn}. ${season().grows.length ? season().grows.join(' and ') + ' crops grow' : 'nothing grows'}.`); }
    if (S.weather) { S.weather.left -= dt; if (S.weather.left <= 0) S.weather = null; } else if (!quiet) for (const w of D.weathers) if (Math.random() < w.p * dt) { S.weather = { id: w.id, left: w.lasts }; S.water = Math.max(0, Math.min(waterCap(), S.water + w.water)); note(`${w.name}.`); break; }
    const wmul = S.weather ? leaf('weathers', S.weather.id).mul : 1; const beastMul = S.beasts.reduce((a, id) => a * leaf('beasts', id).mul, 1);
    S.water = Math.max(0, S.water - 0.2 * Object.keys(S.fields).length * dt); const dry = S.water <= 0 ? 0.5 : 1;
    for (const [fid, f] of Object.entries(S.fields)) { if (!f.crop) continue; const c = leaf('crops', f.crop), F = leaf('fields', fid); const grows = season().grows.includes(c.season) ? season().mul : 0.1;
      const tool = S.tools.map(id => leaf('tools', id)).filter(t => t.on === F.soil).reduce((a, t) => a * t.mul, 1); const fence = S.fences.length ? Math.max(...S.fences.map(id => leaf('fences', id).keep)) : 0.8;
      f.grown += dt * grows * wmul * dry; if (f.grown >= c.days) { const got = Math.round(c.harvest * F.yield * F.size * tool * beastMul * fence); f.crop = null; f.grown = 0; S.harvested += got;
        if (S.stores.length && S.store + got <= storeCap()) { S.store += got; note(`${c.name} came in from ${F.name}: ${fmt(got)} to the store.`); } else { credit(got, `${c.plant} sold at the gate`); note(`${c.name} came in from ${F.name}: ${fmt(got)} HEZE at the gate.`); } } }
    for (const id of S.markets) { const m = leaf('markets', id); if (Math.floor(S.day / m.every) > Math.floor((S.day - dt) / m.every) && S.store > 0) { const got = Math.round(S.store * m.price); credit(got, `the store sold at ${m.where}`); note(`Market day at ${m.where}: ${fmt(S.store)} in the store fetched ${fmt(got)} HEZE at ×${m.price}.`); S.sold += got; S.store = 0; } }
    const eats = S.beasts.reduce((a, id) => a + leaf('beasts', id).eats, 0); if (eats && S.store > 0) S.store = Math.max(0, S.store - eats * dt * 0.1); }
  const away = Math.min((Date.now() - S.saved) / 1000, 8 * 3600); if (away > 5) { let left = away; while (left > 0) { const d = Math.min(5, left); step(d, true); left -= d; } note(`Away ${Math.round(away / 60)} min: the farm kept on.`); }

  let picked = null;
  const stats = [['heze', 'HEZE'], ['season', 'the season'], ['weather', 'the sky'], ['water', 'water'], ['store', 'the store'], ['day', 'the farm']];
  $('#stats').append(...stats.map(([id, label]) => el('div', { class: 'stat', id: 'st-' + id }, el('b', {}, label), el('span'), el('i'))));
  const setStat = (id, v, i) => { const s = $('#st-' + id); s.children[1].textContent = v; s.children[2].textContent = i || ''; };
  const chain = id => { const l = [...D.fields, ...D.crops, ...D.tools, ...D.weathers, ...D.seasons, ...D.beasts, ...D.waters, ...D.fences, ...D.stores, ...D.markets].find(x => x.id === id); return l ? `<code>${l.id}</code> ← <code>${l.wovenBy}</code> ← <code>${l.wovenBy.replace(/^l2-/, 'l3-').replace(/-\d+$/, '')}</code> ← <code>l4-${l.kind}</code> ← <code>loom.mjs</code>` : ''; };
  function buildFields() { const box = $('#fields'); box.innerHTML = ''; for (const f of D.fields) { const owned = S.fields[f.id]; const c = owned && owned.crop ? leaf('crops', owned.crop) : null;
      box.append(el('div', { class: 'card' + (owned ? ' done' : '') + (picked === f.id ? ' on' : ''), style: picked === f.id ? 'border-color:var(--gold)' : null, onclick: () => { if (owned) { picked = picked === f.id ? null : f.id; render(); $('#chain').innerHTML = chain(f.id); } } }, el('b', {}, f.name), el('span', { class: 'n' }, owned ? (c ? `${c.plant} · ${Math.floor(owned.grown)}/${c.days} d` : picked === f.id ? 'picked: sow a crop' : 'fallow · click to pick') : `${fmt(f.cost)} HEZE`), el('p', {}, `yield ×${f.yield} · ${f.soil} · ${f.lie}`),
        owned ? '' : el('button', { disabled: Dk.heze < f.cost ? 'true' : null, onclick: ev => { ev.stopPropagation(); if (debit(f.cost, f.name)) { S.fields[f.id] = { crop: null, grown: 0 }; note(`Bought ${f.name}.`); save(); render(); } } }, 'Buy'))); } }
  function buildCrops() { const box = $('#crops'); box.innerHTML = ''; const f = picked && S.fields[picked]; for (const c of D.crops) { const ok = f && !f.crop && Dk.heze >= c.seed; const inSeason = season().grows.includes(c.season);
      box.append(el('div', { class: 'card' }, el('b', {}, c.name), el('span', { class: 'n' }, `${c.seed} seed · ${c.harvest}/size`), el('p', {}, `${inSeason ? 'in season now' : 'out of season: grows at a tenth'} · sown in ${c.season}`), el('button', { disabled: ok ? null : 'true', onclick: () => { if (debit(c.seed, `${c.plant} seed`)) { S.fields[picked].crop = c.id; S.fields[picked].grown = 0; note(`Sowed ${c.plant} in ${leaf('fields', picked).name}.`); $('#chain').innerHTML = chain(c.id); save(); render(); } } }, f ? (f.crop ? 'field is growing' : 'Sow here') : 'pick a field'))); } }
  function buildThings() { const box = $('#things'); box.innerHTML = ''; const groups = [['tools', 'tool'], ['beasts', 'beast'], ['waters', 'water'], ['fences', 'fence'], ['stores', 'store'], ['markets', 'market']];
    for (const [kind, key] of groups) for (const t of D[kind]) { const have = S[kind].includes(t.id);
      box.append(el('div', { class: 'card' + (have ? ' done' : ''), onclick: () => { $('#chain').innerHTML = chain(t.id); } }, el('b', {}, `${key} · ${t.name}`), el('span', { class: 'n' }, have ? 'kept' : `${fmt(t.cost)} HEZE`), el('p', {}, key === 'tool' ? `×${t.mul} on ${t.on}` : key === 'beast' ? `×${t.mul} on every harvest, eats ${t.eats} from the store a day` : key === 'water' ? `+${t.holds} held` : key === 'fence' ? `keeps ${t.keep} of the yield` : key === 'store' ? `+${t.holds} kept for the market` : `sells the store at ×${t.price} every ${t.every} days`),
        have ? '' : el('button', { disabled: Dk.heze < t.cost ? 'true' : null, onclick: ev => { ev.stopPropagation(); if (debit(t.cost, t.name)) { S[kind].push(t.id); note(`${t.name}.`); save(); render(); } } }, 'Keep'))); } }
  function render() { setStat('heze', fmt(Dk.heze), 'the shared docket'); setStat('season', season().turn, `${Math.ceil(S.seasonLeft)} days left · ×${season().mul}`); setStat('weather', S.weather ? leaf('weathers', S.weather.id).sky : 'fair', S.weather ? `${Math.ceil(S.weather.left)} days · ×${leaf('weathers', S.weather.id).mul}` : '×1'); setStat('water', `${Math.floor(S.water)} / ${waterCap()}`, S.water <= 0 ? 'dry: everything at half' : 'held'); setStat('store', `${fmt(S.store)} / ${fmt(storeCap())}`, S.markets.length ? 'sold on market days' : 'no market: sold at the gate'); setStat('day', `day ${Math.floor(S.day)}`, `${fmt(S.harvested)} harvested · ${fmt(S.sold)} HEZE at market`);
    buildFields(); buildCrops(); buildThings(); $('#log').innerHTML = S.log.map(l => `<div><b>d${l.t}</b>${l.m}</div>`).join(''); $('#clock').textContent = `${Object.keys(S.fields).length} fields · ${S.tools.length + S.beasts.length + S.waters.length + S.fences.length + S.stores.length + S.markets.length} things kept`; }
  $('#wipe').onclick = () => { if (confirm('Clear the land? Fields and things go; the docket stays.')) { S = fresh(); S.grant = true; save(); render(); } };
  const cv = $('#land'), g = cv.getContext('2d');
  function draw(t) { const W = cv.width = cv.clientWidth, H = cv.height; const w = S.weather ? leaf('weathers', S.weather.id) : null; const sky = g.createLinearGradient(0, 0, 0, H); sky.addColorStop(0, w && w.sky === 'frost' ? '#1a2434' : w && w.sky === 'drought' ? '#3a2a14' : '#142a3a'); sky.addColorStop(1, '#2a4a2a'); g.fillStyle = sky; g.fillRect(0, 0, W, H);
    const owned = Object.keys(S.fields); const n = Math.max(1, D.fields.length); D.fields.forEach((f, i) => { const x = 10 + i * ((W - 20) / n), fw = (W - 20) / n - 6, mine = S.fields[f.id]; g.fillStyle = mine ? ({ loam: '#5a4a2a', silt: '#4a4a3a', clay: '#6b4a3a', chalk: '#7a7a6a', peat: '#3a3020', sand: '#8a7a4a' })[f.soil] : '#1e3a2a'; g.fillRect(x, H * .5, fw, H * .45);
      if (mine && mine.crop) { const c = leaf('crops', mine.crop), p = Math.min(1, mine.grown / c.days); g.strokeStyle = '#9ad36a'; g.lineWidth = 2; for (let k = 0; k < 8; k++) { const cx = x + 6 + k * (fw - 12) / 7, h = 6 + p * 30 + Math.sin(t / 700 + k + i) * 2; g.beginPath(); g.moveTo(cx, H * .5); g.lineTo(cx + Math.sin(t / 900 + k) * 2, H * .5 - h); g.stroke(); } }
      g.fillStyle = 'rgba(239,233,220,.6)'; g.font = '10px system-ui'; g.textAlign = 'left'; g.fillText(mine ? (mine.crop ? leaf('crops', mine.crop).plant : 'fallow') : `${f.size} · ${fmt(f.cost)}`, x + 3, H - 6); });
    if (w && (w.sky === 'rain' || w.sky === 'hail')) { g.strokeStyle = 'rgba(180,200,255,.4)'; for (let i = 0; i < 60; i++) { const x = (i * 97 + t / 4) % W, y = (i * 53 + t / 3) % H; g.beginPath(); g.moveTo(x, y); g.lineTo(x - 2, y + 8); g.stroke(); } }
    if (w && w.sky === 'fog') { g.fillStyle = 'rgba(200,210,220,.25)'; g.fillRect(0, 0, W, H); }
    g.fillStyle = 'rgba(239,233,220,.8)'; g.font = '11px system-ui'; g.textAlign = 'left'; g.fillText(`${season().turn} · ${w ? w.sky : 'fair'} · water ${Math.floor(S.water)} · store ${fmt(S.store)}`, 8, 16); requestAnimationFrame(draw); }
  render(); requestAnimationFrame(draw); setInterval(() => { step(1); render(); }, 1000); setInterval(save, 5000); addEventListener('beforeunload', save);
})();
