#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   guild.mjs — builds guild.html: the board that settles the harvest guarantee,
   and the quest board, which is authored rather than derived.

   TWO DEMONSTRATIONS AND A JOB LIST.

   1 THE LADDER. One newcomer, a hundred units of output, five ranks above
     them. Without the guarantee each rank takes a cut of what passes up and
     the newcomer keeps 41 of 100 — 59 of it reaching people who contributed
     nothing to it, by rank alone. With the guarantee they keep 100 and the
     ranks above earn from their own. Same output, same ladder, one term.

   2 THE RENAME DEFEATS IT ANYWAY, which is the entry's stated limit made
     watchable. Leave the guarantee ON and reclassify the contribution as
     pooled, and the guaranteed stream becomes a share of a pool rather than
     a claim on your own output — 2 of 100 across fifty members. The transfer
     was enforced perfectly. The definition ate it upstream, where the
     contract does not reach.

   3 THE QUESTS ARE AUTHORED, NOT DERIVED. An earlier draft generated one job
     per knowledge-base entry, which meant the board grew every time somebody
     wrote an entry — a loop, shipped as a feature. Quests now live in
     templates-quest/ with four required fields (giver, object, done,
     produces) and are refused by quests.mjs if `produces` names a quest, if
     `done` depends on another one, or if the requires graph cycles or runs
     deeper than three.

     None of them is worth more than another. There are no points, no tiers
     and no order: doing one is +1 and which one you did is not comparable.
     A quest board with a difficulty rating is a ladder, and this whole page
     is about what a ladder does.

       node guild.mjs
   ═══════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const rich = (s) => esc(s)
  .replace(/`([^`]+)`/g, '<code>$1</code>')
  .replace(/\b([A-Z][A-Z ’']{3,}[A-Z])\b/g, '<em>$1</em>');

const kb = JSON.parse(readFileSync('kb.json', 'utf8'));

/* THE QUESTS COME FROM templates-quest/, NOT FROM kb.json, AND THAT IS A FIX.
   The first draft of this file generated one job per knowledge-base entry and
   said so as though it were a feature: "write a new entry and a new job appears
   without anybody maintaining a second list." That is a board that grows by
   being read — a loop with a story on it — and it would have filled up with
   work about the board. Quests are authored, validated by quests.mjs against
   three anti-recursion rules, and compiled separately. */
const QDIR = 'templates-quest';
const quests = readdirSync(QDIR).filter((f) => f.endsWith('.json')).sort()
  .map((f) => JSON.parse(readFileSync(join(QDIR, f), 'utf8')));

/* the ladder, computed rather than typed */
const CUT = 0.20, RANKS = 5, START = 100;
let left = START; const rows = [];
for (let r = 2; r <= RANKS; r++) {
  const take = left * CUT;
  rows.push({ r, take, left: left - take });
  left -= take;
}
const kept = left, taken = START - kept;
const POOL = 50, pooled = START / POOL;

const CLS = { concept: 'survey', mechanism: 'field work', figure: 'interview',
              number: 'measurement' };

const SKY = readFileSync('.sky-block.txt', 'utf8').replace('#060a08', '#0b0910');

writeFileSync('guild.html', `<title>The Guild &middot; what a ladder takes, and ${quests.length} jobs</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<!--
  THE GUILD — the board that settles the harvest guarantee, and the quest board.

  Generated by guild.mjs. The ${quests.length} quests are AUTHORED, in
  templates-quest/, and are not derived from the knowledge base — an earlier
  draft made one job per entry and said so as though it were a feature, which
  is a board that grows by being read. quests.mjs refuses any quest whose
  produces-field names a quest, whose done-condition depends on finishing
  another, or whose prerequisites cycle or run deeper than three.

  THE LADDER. One newcomer, ${START} units, ${RANKS} ranks. At a ${CUT * 100}%
  cut per rank the newcomer keeps ${kept.toFixed(1)} and ${taken.toFixed(1)}
  reaches people who contributed nothing to it — by rank, with nobody breaking a
  rule. Turn the guarantee on and the same ladder takes nothing, because the
  ranks above are now earning from their own contribution instead.

  AND THE RENAME STILL BEATS IT. Leave the guarantee on and reclassify the
  contribution as pooled: the guaranteed stream becomes a share of a pool rather
  than a claim on your own output, and across ${POOL} members that is
  ${pooled.toFixed(1)} of ${START}. The transfer was enforced perfectly. The
  definition ate it upstream, where a contract does not reach.

  No quest is worth more than another and none of them carries a number.
  A quest board with a difficulty rating is a ladder.

  No script decides anything on this page.
-->
<style>
  :root{
    --void:#0b0910; --card:#151020; --card2:#1a1427; --edge:#2f2540;
    --ink:#ece7f4; --dim:#9b8fb0; --bone:#e4d9b8;
    --keep:#5fd6a4; --take:#e0705a; --gold:#e0b155; --vio:#9d8ae0;
    --key:#6ec6ff;
  }
  *{box-sizing:border-box}
  body{margin:0;padding:20px 16px 56px;color:var(--ink);background:var(--void);
    font:13.5px/1.66 ui-rounded,system-ui,-apple-system,sans-serif;
    background-image:
      radial-gradient(circle at 16% -6%,rgba(157,138,224,.12),transparent 46%),
      radial-gradient(circle at 88% 100%,rgba(224,177,85,.07),transparent 42%)}
  .w{max-width:1040px;margin:0 auto}
  header{display:flex;align-items:baseline;gap:12px;flex-wrap:wrap;
    border-bottom:1px solid var(--edge);padding-bottom:12px;margin-bottom:16px}
  h1{margin:0;font-size:22px;letter-spacing:-.018em;color:var(--bone)}
  header .sub{color:var(--dim);font-size:11.5px;max-width:66ch}
  header .tag{margin-left:auto;font:9px/1 ui-monospace,monospace;letter-spacing:.2em;
    text-transform:uppercase;color:var(--vio);border:1px solid var(--vio);
    border-radius:4px;padding:4px 9px}
  h2{font:9.5px/1 ui-monospace,Menlo,monospace;letter-spacing:.2em;
    text-transform:uppercase;color:var(--dim);margin:28px 0 10px;font-weight:600;
    display:flex;justify-content:space-between;align-items:baseline;gap:12px}
  h2 b{color:var(--bone);font-family:inherit;letter-spacing:0;text-transform:none;
    font-size:10.5px;font-weight:600}
  p.n{color:var(--dim);font-size:11.5px;line-height:1.72;margin:10px 0 0;max-width:94ch}
  p.n b{color:var(--ink)} p.n em{font-style:normal;color:var(--gold)}
  a{color:var(--gold)}
  code{font:10.5px ui-monospace,monospace;color:var(--bone);background:#0d0a13;
    border:1px solid var(--edge);border-radius:4px;padding:1px 5px}
  .panel{background:linear-gradient(180deg,var(--card),var(--card2));
    border:1px solid var(--edge);border-radius:13px;padding:16px 17px}

  .opts{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}
  .opts input{position:absolute;opacity:0;width:1px;height:1px}
  .opts label{cursor:pointer;font:11.5px/1 ui-monospace,monospace;padding:11px 14px;
    border-radius:9px;border:1px solid var(--edge);color:var(--dim);user-select:none}
  .opts label:hover{color:var(--ink)}
  .opts input:checked + label{border-color:var(--bone);color:var(--bone);
    background:rgba(228,217,184,.10);font-weight:700}
  .opts input:focus-visible + label{outline:2px solid var(--key);outline-offset:2px}

  /* ── the ladder ─────────────────────────────────────────────────────── */
  .lad{display:grid;gap:5px;margin-top:14px}
  .rk{display:grid;grid-template-columns:104px 1fr 78px;gap:12px;align-items:center;
    background:#0d0a13;border:1px solid var(--edge);border-radius:9px;
    padding:9px 12px;font:10.5px/1.4 ui-monospace,monospace}
  .rk b{color:var(--bone);font-size:11px}
  .rk .bar{height:16px;border-radius:3px;background:#151020;overflow:hidden;
    display:flex}
  .rk .bar i{display:block;height:100%}
  .rk .bar .k{background:linear-gradient(90deg,#2f7a5a,var(--keep))}
  .rk .bar .t{background:linear-gradient(90deg,#7a3228,var(--take))}
  .rk u{text-decoration:none;text-align:right;color:var(--dim)}
  .rk.new{border-color:var(--keep)}
  .g:has(#g-on:checked) .rk .t{width:0 !important}
  .g:has(#g-on:checked) .rk .k{width:100% !important}

  .sum{display:grid;gap:10px;grid-template-columns:repeat(3,1fr);margin-top:14px}
  @media (max-width:700px){.sum{grid-template-columns:1fr}}
  .s{background:#0d0a13;border:1px solid var(--edge);border-radius:10px;
    padding:12px 13px}
  .s span{display:block;font:8.5px/1.3 ui-monospace,monospace;letter-spacing:.14em;
    text-transform:uppercase;color:#6d6280;margin-bottom:6px}
  .s b{font:22px/1 ui-monospace,monospace;color:var(--bone)}
  .s.keep b{color:var(--keep)} .s.take b{color:var(--take)}
  .g:has(#g-on:checked) .s-kept b::after{content:"${START}"}
  .g:has(#g-off:checked) .s-kept b::after{content:"${kept.toFixed(1)}"}
  .g:has(#g-on:checked) .s-taken b::after{content:"0"}
  .g:has(#g-off:checked) .s-taken b::after{content:"${taken.toFixed(1)}"}
  .g:has(#g-on:checked) .s-verdict b::after{content:"in force"}
  .g:has(#g-off:checked) .s-verdict b::after{content:"not in force"}
  .g:has(#g-off:checked) .s-verdict b{color:var(--take)}
  .g:has(#g-on:checked) .s-verdict b{color:var(--keep)}

  /* ── the rename ─────────────────────────────────────────────────────── */
  .rn{margin-top:13px;padding:14px 15px;border-radius:10px;background:#0d0a13;
    border:1px solid var(--edge);border-left:3px solid var(--dim);min-height:104px}
  .rn .f{display:block;font:21px/1 ui-monospace,monospace;color:var(--bone);
    margin-bottom:7px}
  .rn .f::after{content:"—"}
  .rn h4{margin:0 0 5px;font-size:13.5px;color:var(--bone)}
  .rn h4::before{content:"Pick a definition."}
  .rn p{margin:0;font-size:12px;color:var(--dim);line-height:1.72;max-width:82ch}
  .d:has(#d-own:checked) .rn{border-left-color:var(--keep)}
  .d:has(#d-own:checked) .rn .f::after{content:"${START} of ${START} reaches you"}
  .d:has(#d-own:checked) .rn h4::before{content:"“What you brought” = your output"}
  .d:has(#d-own:checked) .rn p::before{content:"The guarantee is doing exactly what it says. Your stream is yours, no majority reassigns it, and nobody above you takes a cut by rank. This is the case the contract was written for and it holds perfectly."}
  .d:has(#d-pool:checked) .rn{border-left-color:var(--take)}
  .d:has(#d-pool:checked) .rn .f::after{content:"${pooled.toFixed(1)} of ${START} reaches you"}
  .d:has(#d-pool:checked) .rn h4::before{content:"“What you brought” = a share of the pool"}
  .d:has(#d-pool:checked) .rn p::before{content:"The guarantee is still on and still enforced. Nobody broke it, nobody voted, no majority reassigned anything — the contract executed its terms faithfully and irreversibly. But the contribution was defined as pooled before it reached the contract, so across ${POOL} members the guaranteed stream is a fiftieth. The transfer was enforced. The definition was not, because the definition sits upstream of the code and the code cannot see it."}
  .d:has(#d-hire:checked) .rn{border-left-color:var(--take)}
  .d:has(#d-hire:checked) .rn .f::after{content:"0 of ${START} reaches you"}
  .d:has(#d-hire:checked) .rn h4::before{content:"“What you brought” = work for hire"}
  .d:has(#d-hire:checked) .rn p::before{content:"Reclassified at the door: the output was never yours to have a stream from, so the guarantee is over an empty category and it discharges correctly by paying nothing. Still no rule broken. Still no vote taken. This is the rename, applied to a person instead of a commons, and it is why closing the discretionary path is necessary and not sufficient."}

  /* ── the quests ─────────────────────────────────────────────────────── */
  .q{display:grid;gap:9px;grid-template-columns:repeat(2,1fr);margin-top:14px}
  @media (max-width:860px){.q{grid-template-columns:1fr}}
  .job{background:#0d0a13;border:1px solid var(--edge);border-radius:11px;
    padding:12px 13px;border-left:3px solid var(--jc);display:flex;
    flex-direction:column;gap:7px}
  .job h4{margin:0;font-size:13px;color:var(--bone);display:flex;
    align-items:baseline;gap:8px}
  .job h4 i{font-style:normal;margin-left:auto;font:8px/1 ui-monospace,monospace;
    letter-spacing:.14em;text-transform:uppercase;color:var(--jc)}
  .job .task{margin:0;font-size:11.5px;color:var(--ink);line-height:1.65}
  .job .why{margin:0;font-size:10.5px;color:var(--dim);line-height:1.6;
    padding-top:7px;border-top:1px solid #1e1729}
  .job .why a{color:var(--gold)}
  .j-concept{--jc:#9d8ae0} .j-mechanism{--jc:#6ec6ff}
  .j-figure{--jc:#e0a05a} .j-number{--jc:#5fd6a4}

  body{counter-reset:jobs 0}
  .job{counter-increment:jobs 1}
  .tally{margin-top:14px;padding:12px 14px;border:1px dashed var(--edge);
    border-radius:10px;color:var(--dim);font-size:11px;line-height:1.7}
  .tally b{color:var(--bone)}
  .tally::before{content:counter(jobs);font:17px/1 ui-monospace,monospace;
    color:var(--vio);margin-right:9px}

  footer{margin-top:32px;padding-top:14px;border-top:1px solid var(--edge);
    color:var(--dim);font-size:10.5px;line-height:1.75}
${SKY}</style>

<div class="w">
  <header>
    <h1>The Guild</h1>
    <span class="sub">What a ladder takes when nobody breaks a rule, the one
      term that stops it, the rename that beats the term anyway &mdash; and
      ${quests.length} jobs, none of which is worth more than another.</span>
    <span class="tag">no script</span>
  </header>

  <h2>1 &middot; The ladder <b>one newcomer &middot; ${START} units &middot; ${RANKS} ranks &middot; ${CUT * 100}% a rank</b></h2>
  <div class="g panel">
    <div class="opts">
      <input type="radio" name="g" id="g-off" checked>
        <label for="g-off">no guarantee</label>
      <input type="radio" name="g" id="g-on">
        <label for="g-on">harvest guarantee in force</label>
    </div>
    <div class="lad">
      <div class="rk new"><b>rank 1 &mdash; you</b>
        <span class="bar"><i class="k" style="width:${kept}%"></i><i class="t" style="width:${taken}%"></i></span>
        <u>produces ${START}</u></div>
${rows.map((r) => `      <div class="rk"><b>rank ${r.r}</b>
        <span class="bar"><i class="k" style="width:${(r.left / START * 100).toFixed(1)}%"></i><i class="t" style="width:${(r.take / START * 100).toFixed(1)}%"></i></span>
        <u>takes ${r.take.toFixed(1)}</u></div>`).join('\n')}
    </div>
    <div class="sum">
      <div class="s keep s-kept"><span>reaches you</span><b></b></div>
      <div class="s take s-taken"><span>reaches non-contributors, by rank</span><b></b></div>
      <div class="s s-verdict"><span>the test</span><b></b></div>
    </div>
    <p class="n"><b>Nobody breaks a rule in the left-hand case.</b> Each rank is
      entitled to its cut, each cut is disclosed, each was agreed on joining, and
      ${taken.toFixed(1)} of your ${START} units still reaches people who
      contributed nothing to them &mdash; not by theft, by <em>rank</em>. That is
      the amateur farm from the entry, drawn: to you the guild is a bank, and to
      each of the four above you it is a crop.</p>
    <p class="n">Turn the guarantee on and the same five ranks take nothing,
      because they are now earning from their own contribution instead of from
      yours. The bank half is untouched &mdash; you still got the tools, the
      standing and the customers. <b>What is gone is only the harvest</b>, and
      nobody had to be expelled for it to go.</p>
  </div>

  <h2>2 &middot; The rename beats it <b>the guarantee stays on the whole time</b></h2>
  <div class="d panel">
    <p class="n">The entry says the contract enforces the transfer and not the
      definition. Here is what that costs. <b>The guarantee is in force in all
      three columns below</b> &mdash; enforced, irreversible, unappealable. Only
      the meaning of &ldquo;what you brought&rdquo; changes, and it changes
      upstream, before anything reaches the code.</p>
    <div class="opts">
      <input type="radio" name="d" id="d-own" checked><label for="d-own">your output</label>
      <input type="radio" name="d" id="d-pool"><label for="d-pool">a pool share</label>
      <input type="radio" name="d" id="d-hire"><label for="d-hire">work for hire</label>
    </div>
    <div class="rn"><span class="f"></span><h4></h4><p></p></div>
    <p class="n"><b>Which settles the entry in both directions, and that is the
      point of building it.</b> The guarantee genuinely closes the discretionary
      path &mdash; there is no rank, no vote and no promotion that reassigns your
      stream, and that is worth having. And it is genuinely defeated by a noun,
      because the code cannot see the category it is paying out over. Close the
      discretionary path and the semantic one is still open, which is
      <a href="kb.html#smart-contracts">the contested entry</a> arriving again
      wearing different clothes.</p>
  </div>

  <h2>3 &middot; The jobs <b>${quests.length} of them &middot; every one is a test somebody could fail</b></h2>
  <div class="panel">
    <p class="n">A quest is four things and the template is the definition
      rather than a note about one: a <b>giver</b> who wants it and cannot do it
      themselves, an <b>object</b> in one imperative sentence, a <b>done</b> that
      somebody else can check, and a <b>produces</b> &mdash; what exists
      afterwards that did not before.</p>
    <p class="n"><b>An earlier draft of this page generated one job per
      knowledge-base entry and boasted about it</b> &mdash; write an entry, get a
      job, no second list to maintain. That is a board that grows by being read,
      and it would have filled with work about the board. Quests are authored
      now, and <a href="quests.mjs">quests.mjs</a> refuses any whose
      <code>produces</code> names a quest, whose <code>done</code> depends on
      finishing another one, or whose prerequisites cycle or run deeper than
      three. All four failure classes are tested against it.</p>
    <p class="n"><b>None of them is worth more than another and none carries a
      number.</b> No points, no tiers, no prerequisites, no order. Doing one is
      +1 and which one you did is not comparable to which one somebody else did
      &mdash; because a quest board with a difficulty rating is a ladder, and the
      first two panels on this page are about what a ladder does.</p>
    <div class="q">
${quests.map((e) => `      <article class="job j-${e.class}">
        <h4>${esc(e.term)}<i>${CLS[e.class] || e.class}</i></h4>
        <p class="task">${rich(e.test)}</p>
        <p class="why">${rich(e.short)} &nbsp;<a href="kb.html#${esc(e.id)}">the entry &rarr;</a></p>
      </article>`).join('\n')}
    </div>
    <div class="tally">jobs on the board, and <b>nothing happens at
      ${quests.length}.</b> No completion state, no rank to reach, no reward for
      the set, and no difficulty on any of them &mdash; a quest board with a
      difficulty rating is a ladder, and the first two panels here are about what
      a ladder does. The board exists because a test nobody runs is a claim, and
      a claim that has never been attacked is worth less than a finding that
      has.</div>
  </div>

  <footer>
    Generated by <a href="guild.mjs">guild.mjs</a>. Quests from
    <a href="quests.mjs">templates-quest/</a>, ${quests.length} of them, each
    checked against three anti-recursion rules. Ladder computed at ${CUT * 100}%
    per rank over ${RANKS} ranks; pool share over ${POOL} members. The knowledge
    base has ${kb.entries.length} entries and this board does not derive from
    it, on purpose.
    <br><a href="kb.html#the-harvest-guarantee">the harvest guarantee</a> &middot;
    <a href="baseline.html">the baseline</a> &middot;
    <a href="syndicate.html">spotting a syndicate</a> &middot;
    <a href="index.html">the yard</a>
  </footer>
</div>
<script src="automat.js"></script>
<script src="devmode.js"></script>
`);

console.log(`guild.html · ${quests.length} authored quests · kb has ${kb.entries.length} entries and is not the source`);
console.log(`  ladder: newcomer keeps ${kept.toFixed(1)} of ${START}, ` +
  `${taken.toFixed(1)} to rank`);
console.log(`  rename: own ${START} · pool ${pooled.toFixed(1)} · work-for-hire 0`);
