/* Generated by hub.mjs from kb.json — do not edit, edit the JSON and re-run.
   11 of 33 knowledge-base entries have a game
   trigger. Each carries its TEST, which the Hub runs against the live board
   rather than printing. Unlocking grants nothing: a knowledge system that pays
   out makes knowing a currency, and a currency you cannot refuse is the thing
   the base spends its whole length arguing against. */
window.HUB = [
 {
  "id": "fungibility",
  "term": "Fungibility",
  "cls": "concept",
  "settled": "settled",
  "short": "No unit is worth more than another, and there is no way to write the function that would prefer one.",
  "test": "Write the preference function over two units. If it compiles, they are not fungible. If it does not, ask what the syndicate would have to add before it could — that addition is the attack.",
  "unlock": "Let the commons read bare, and watch nothing fail."
 },
 {
  "id": "the-minimum-cycle",
  "term": "What it takes to start something",
  "cls": "concept",
  "settled": "settled",
  "short": "Not the most important thing. The smallest closed loop in which every part is fed by another part.",
  "test": "Invert the dependency graph and look for cycles, not for maxima. If your proposed start has no path back to itself, it is a root and not a start, and it will sit idle producing nothing until you build the return arrow.",
  "unlock": "Build every root the template has, and nothing else, until it is clear that nothing is happening."
 },
 {
  "id": "the-window",
  "term": "The window",
  "cls": "number",
  "settled": "settled",
  "short": "583.92 days between one departure and the next. Nothing you can spend shortens the wait.",
  "test": "Ask what would shorten it. If the answer offered is budget, headcount, or a better vendor, that is a different constraint being described. The only thing that moves a departure inside the window is propellant, and what it buys is a worse transfer, not an earlier arrival.",
  "unlock": "Let a window open."
 },
 {
  "id": "the-passage",
  "term": "The passage",
  "cls": "number",
  "settled": "settled",
  "short": "146 days out, on the minimum-energy path. The fast way there is not the straight one.",
  "test": "Compute the transfer period from the two semi-major axes and halve it. If a quoted passage time is much shorter than that, it is not a minimum-energy transfer, and the difference is propellant somebody has to launch. Ask for the delta-v alongside the duration; a duration on its own is not a plan.",
  "unlock": "Complete one leg of the relay, either way."
 },
 {
  "id": "the-light-delay",
  "term": "The light delay",
  "cls": "number",
  "settled": "settled",
  "short": "2.2 minutes at closest, 14.3 at furthest, one way. There is no live conversation with Venus.",
  "test": "Time your loops. List every procedure whose correct response must arrive in under 4.4 minutes. That list is not a communications problem — it is the exact scope of the authority you have to delegate to the far end before departure, and it is the same list whether Venus is near or far.",
  "unlock": "Fly past the three-quarter mark, where the correction lag passes two minutes."
 },
 {
  "id": "the-relay",
  "term": "The relay",
  "cls": "mechanism",
  "settled": "settled",
  "short": "A relay race, not a haul. The baton crosses the whole distance; no runner does. Nothing is lost at the exchange and the runner goes home and starts again.",
  "test": "Ask who is responsible for the cargo at the midpoint. If it is the same party as at departure, it is a haul with extra stops and you are paying the whole distance. In a relay the answer is a station, with different authority from the one before it, and there is a defined moment when responsibility changed hands.",
  "unlock": "Take a delivery that carries a held window with it — two or more at once."
 },
 {
  "id": "the-baton",
  "term": "The baton",
  "cls": "concept",
  "settled": "settled",
  "short": "The only object in the system whose journey is the point. The hull is not the baton, and confusing the two is the commonest error there is.",
  "test": "Name the baton, then read your own dashboard. If what it measures is carriers — utilisation, throughput, disposals, uptime — and not the baton's position, you are optimising the things that go home at the end of the shift. Ask where the baton is and how long it has been there; if nobody owns that number, nobody is watching the only journey in the system.",
  "unlock": "Put a manifest line into Plant, and ship the thing that harvests rather than the harvest."
 },
 {
  "id": "the-exchange",
  "term": "The exchange",
  "cls": "mechanism",
  "settled": "settled",
  "short": "The only place a relay fails, and the only place authority changes. For the length of it the object has either two owners or none.",
  "test": "Ask both parties when responsibility changed hands and check whether they name the same event. If either names a period rather than an event, or if they name different events, you have found the gap — and it is the same gap whether or not anything has fallen through it yet. Then ask who could verify the answer without having been present.",
  "unlock": "Miss an exchange and have the baton held at a station."
 },
 {
  "id": "the-injector",
  "term": "The injector",
  "cls": "figure",
  "settled": "settled",
  "short": "What the operator of an automated thing actually is. Two verbs: start it, and stop it. Steering is not on the list.",
  "test": "Count the operator's verbs and check whether mid-run adjustment is one of them. If it is, the system is assisted rather than automated and somebody is still flying it. If it is not, find the last moment a decision could have changed the outcome — that moment is the operator's entire job, and if the interface gives it the same weight as everything else, the interface is wrong.",
  "unlock": "Press START. That is the whole trigger and it is the whole point."
 },
 {
  "id": "the-prior-condition",
  "term": "The prior condition",
  "cls": "concept",
  "settled": "settled",
  "short": "A syndicate does not recruit. It selects for a condition that was already there — and what it sells is not money, it is predictability.",
  "test": "Ask what the structure supplies that the alternative does not. If the answer is money, the exit is priceable and people leave when a better offer arrives. If the answer is predictability, the exit is not priceable, better offers do nothing, and any counter that competes only on money will fail — because it is not competing on the thing being bought. Then check your own door: count the steps between arriving and participating that require somebody to vouch for you.",
  "unlock": "Switch base template — the same board, read against a different roster."
 },
 {
  "id": "hydrogen",
  "term": "Hydrogen is the only scarcity",
  "cls": "number",
  "settled": "working",
  "short": "Carbon, oxygen, nitrogen and sulphur are all abundant on Venus. Hydrogen is not, and everything wet depends on it.",
  "test": "Trace any requirement in the profiles back along its inputs. If it terminates at water and the water terminates at hydrogen, it is in the constrained set. If a proposal claims to avoid this, ask where its hydrogen comes from and in what mass.",
  "unlock": "Take a delivery. Any delivery."
 }
];
