#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   hub.mjs — builds hub.js, the Knowledge Hub, out of kb.json.

   The knowledge base has twenty-seven entries and every one carries a TEST:
   the thing you could do that would show it false. That is the useful half and
   it is wasted on a page you read.

   So the Hub does not hand you an article. It runs the entry's test against
   YOUR BOARD and reports what it found — your dependency graph, your counters,
   your held windows. An entry unlocks when the game has actually demonstrated
   it, and then it becomes an instrument you can point at your own save.

   WHAT IT DELIBERATELY DOES NOT DO
   Unlocking grants nothing. No bonus, no multiplier, no gated mechanic. A
   knowledge system that pays out makes knowing a currency, and a currency you
   cannot refuse is the thing this base has spent twenty-seven entries arguing
   against. The Hub is a record and an instrument, and those are enough.

   Entries appear here only if kb.json gives them a `game` block:
       "game": { "unlock": "<what the board has to do>" }
   The check itself lives in game.html, keyed by entry id, because it needs the
   live state. This file carries the prose so kb.json stays the one source.

       node hub.mjs
   ═══════════════════════════════════════════════════════════════════════════ */
import { readFileSync, writeFileSync } from 'node:fs';

const doc = JSON.parse(readFileSync('kb.json', 'utf8'));
const picked = doc.entries.filter((e) => e.game && e.game.unlock);

const out = picked.map((e) => ({
  id: e.id, term: e.term, cls: e.class, settled: e.settled,
  short: e.short, test: e.test, unlock: e.game.unlock
}));

writeFileSync('hub.js',
`/* Generated by hub.mjs from kb.json — do not edit, edit the JSON and re-run.
   ${out.length} of ${doc.entries.length} knowledge-base entries have a game
   trigger. Each carries its TEST, which the Hub runs against the live board
   rather than printing. Unlocking grants nothing: a knowledge system that pays
   out makes knowing a currency, and a currency you cannot refuse is the thing
   the base spends its whole length arguing against. */
window.HUB = ${JSON.stringify(out, null, 1)};
`);

console.log(`hub.js · ${out.length} of ${doc.entries.length} entries carry a game trigger`);
out.forEach((e) => console.log(`  ${e.id.padEnd(22)} ${e.unlock}`));
const missing = doc.entries.filter((e) => !e.game).length;
console.log(`\n${missing} entries have no trigger — they are read, not earned, and that is` +
  ` correct for most of them. Add a "game" block to kb.json to pull one in.`);
