#!/usr/bin/env node
/* siege.mjs — builds siege.html: Troy as a tower defence, ten years against
   an AI that is seven levels ahead, paid in HEZE.

   Every tower is a template in templates-prince/ (fourteen sons of Priam,
   each with a kind, a reach, a rate and one thing only he does). The waves
   are the yard's demons (templates-demon/) wearing Achaean names, scaled by
   the AI's level, which is always yours plus seven. The spells are the
   warlock's (templates-spell/) with their own costs and cooldowns. The wall is
   the warlock's wall: 8.3 m of dead ground at its foot that most towers cannot
   see into, which is where the diggers go.

   Once a year there is a wedding, and it is a blind auction: three suitors
   behind veils, a dowry each, and one of them, at the last wedding for
   certain, is Paris. You bid HEZE without knowing; so does the AI. Helenus on
   the wall lifts the veils.

   Generated from the templates so the page cannot drift from them.
       node siege.mjs
*/
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
const load = d => readdirSync(d).filter(f => f.endsWith('.json') && !f.startsWith('_')).map(f => JSON.parse(readFileSync(d + '/' + f, 'utf8'))).sort((a, b) => +a.order - +b.order);
const princes = load('templates-prince'), demons = load('templates-demon'), spells = load('templates-spell');
const wall = JSON.parse(readFileSync('api/warlock.json', 'utf8')); delete wall.demons; delete wall.spells;
const page = readFileSync('siege.page.js', 'utf8');
const DEF = { princes, demons, spells, wall, years: 10, ahead: 7, treasury: 60000, waveEvery: 30, weddingEvery: 365, breachMax: 9,
  suitors: [
    { id: 'aeneas', name: 'Aeneas', dowry: { kind: 'garrison', x: 1.15 }, text: 'Dardanian. His men on the wall: every tower ×1.15.' },
    { id: 'sarpedon', name: 'Sarpedon', dowry: { kind: 'slot' }, text: 'Lycian. Brings masons: one more tower slot.' },
    { id: 'memnon', name: 'Memnon', dowry: { kind: 'heze', x: 40000 }, text: 'Ethiopian, and rich. A bride price in HEZE.' },
    { id: 'penthesilea', name: 'Penthesilea', dowry: { kind: 'repair', x: 3 }, text: 'Amazon. Three breaches closed the day she arrives.' },
    { id: 'rhesus', name: 'Rhesus', dowry: { kind: 'mana', x: 10 }, text: 'Thracian, with horses. Ten more of whatever the spells run on.' },
    { id: 'eurypylus', name: 'Eurypylus', dowry: { kind: 'upgrade' }, text: 'Mysian. One tower upgraded for nothing.' },
    { id: 'paris', name: 'Paris', dowry: { kind: 'helen' }, text: 'You did not know it was Paris. Helen comes home with him, the AI gains two levels for good, and the war you were fighting becomes the one in the story.' },
  ] };
const html = `<title>The siege of Troy &middot; ten years against an AI seven levels ahead</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!--
  THE SIEGE — tower defence, paid in HEZE.

  Generated by siege.mjs from templates-prince/ (${princes.length} princes), templates-demon/
  (${demons.length} shapes), templates-spell/ (${spells.length} spells) and the wall in api/warlock.json.
  You are Priam. The AI is the fleet, and its level is always yours plus ${DEF.ahead}.
  The fight is ten years long, one day a second, and it only moves while you
  watch it; a tower defence you cannot see is not one. The docket is the
  ground landing's and Troy's: HEZE in, HEZE out, nothing here is money.
  No faces. Glyphs, walls, veils.
  SCRIPT: yes, and marked.
-->
<style>
  :root{--void:#0b0d12;--panel:#151922;--panel2:#1c2230;--edge:#2b3445;--ink:#efe9dc;--dim:#95a0b3;--gold:#f2c98a;--venus:#f0a83c;--ok:#6fd4a8;--bad:#e06f5a;--sea:#2f6f9f}
  *{box-sizing:border-box}
  html,body{margin:0;background:var(--void);color:var(--ink);font:13px/1.45 ui-rounded,system-ui,-apple-system,sans-serif}
  header{padding:12px 16px 6px;display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}
  header h1{margin:0;font-size:19px;color:var(--gold);font-weight:600}header small{color:var(--dim)}
  #field{display:block;width:100%;height:340px;background:#0e1a24;cursor:crosshair}
  main{padding:8px 12px 30px;max-width:1200px;margin:0 auto;display:grid;gap:10px}
  .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:6px}
  .stat{background:var(--panel);border:1px solid var(--edge);border-radius:10px;padding:7px 10px}
  .stat b{display:block;font-size:10.5px;color:var(--dim);font-weight:500;text-transform:uppercase;letter-spacing:.06em}
  .stat span{font-size:17px;font-variant-numeric:tabular-nums}.stat i{font-style:normal;color:var(--dim);font-size:11px;display:block}
  .cols{display:grid;grid-template-columns:1.2fr 1fr;gap:10px}@media (max-width:860px){.cols{grid-template-columns:1fr}}
  section{background:var(--panel);border:1px solid var(--edge);border-radius:12px;padding:10px}
  section h2{margin:0 0 6px;font-size:11.5px;color:var(--dim);text-transform:uppercase;letter-spacing:.08em;font-weight:600}
  section h2 i{font-style:normal;text-transform:none;letter-spacing:0;font-weight:400;margin-left:6px}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:6px}
  .card{background:var(--panel2);border:1px solid var(--edge);border-radius:10px;padding:8px;display:flex;flex-direction:column;gap:3px;cursor:pointer}
  .card.on{border-color:var(--gold)}.card.built{border-color:var(--ok)}.card.locked{opacity:.5}
  .card h3{margin:0;font-size:13px;display:flex;justify-content:space-between;gap:6px}.card h3 span{color:var(--gold);white-space:nowrap;font-weight:500}
  .card p{margin:0;color:var(--dim);font-size:11.5px}
  button{font:inherit;color:var(--ink);background:var(--panel2);border:1px solid var(--edge);border-radius:8px;padding:6px 10px;cursor:pointer}
  button:hover:not(:disabled){border-color:var(--gold)}button:disabled{opacity:.45;cursor:not-allowed}button.primary{background:#2a2036;border-color:var(--venus)}
  .row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
  .spell{display:flex;flex-direction:column;align-items:center;gap:2px;min-width:74px}
  .spell b{font-size:18px}.spell small{color:var(--dim)}
  .badge{display:inline-block;background:var(--panel);border:1px solid var(--edge);border-radius:999px;padding:1px 8px;font-size:11px;color:var(--dim)}.badge.hot{border-color:var(--venus);color:var(--venus)}.badge.ok{border-color:var(--ok);color:var(--ok)}
  input[type=number]{font:inherit;color:var(--ink);background:var(--panel2);border:1px solid var(--edge);border-radius:8px;padding:6px 8px;width:130px}
  .log{font-size:12px;color:var(--dim);max-height:180px;overflow:auto}.log div{border-bottom:1px solid var(--edge);padding:2px 0}.log b{color:var(--ink);font-weight:500;margin-right:6px}
  .veil{background:linear-gradient(135deg,#2a2036,#1c2230);border:1px dashed var(--edge)}
  footer{padding:10px 16px 24px;color:var(--dim);font-size:12px;max-width:1200px;margin:0 auto}footer a{color:var(--sea);text-decoration:none}
</style>
<header><h1>The siege of Troy</h1><small>ten years, one day a second, against a fleet seven levels ahead of you</small><span style="flex:1"></span><small id="clock"></small></header>
<canvas id="field" width="1200" height="340"></canvas>
<main>
  <div class="stats" id="stats"></div>
  <div class="cols">
    <div>
      <section><h2>The princes<i>pick one, then click an empty slot on the wall; click a built tower to upgrade it</i></h2><div class="grid" id="princes"></div></section>
      <section><h2>Spells<i>the warlock's six; they run on their own reserve, one a day</i></h2><div class="row" id="spells"></div><p id="spell-hint" style="color:var(--dim);margin:6px 0 0"></p></section>
    </div>
    <div>
      <section><h2>The wedding<i>once a year, behind veils; you and the AI bid blind; one of them is Paris</i></h2><div id="wedding"></div></section>
      <section><h2>The fleet<i>the AI's next wave, and what it is</i></h2><div id="fleet"></div></section>
      <section><h2>The record</h2><div class="log" id="log"></div><div class="row" style="margin-top:6px"><button id="pause">Pause</button><button id="wipe">Start the siege again</button></div></section>
    </div>
  </div>
</main>
<footer>Princes from <a href="index.html">templates-prince/</a>; shapes and spells from <a href="warlock.html">the warlock</a>; the docket from <a href="descent.html">the ground landing</a> and <a href="troy.html">Troy</a>. Nothing here is money. <a href="arcade.html">← the arcade</a> · <a href="index.html">the yard</a></footer>
<script id="def-json" type="application/json">${JSON.stringify(DEF).replace(/<\//g, '<\\/')}</script>
<script>
${page}
</script>
`;
writeFileSync('siege.html', html);
console.log(`wrote siege.html · ${princes.length} princes · ${demons.length} shapes · ${spells.length} spells · ${DEF.suitors.length} suitors · ${html.length} bytes`);
