#!/usr/bin/env node
/* town.mjs — the interface after the village, woven from the village's templates.

   Each village template weaves one thing in the town (templates-town/): a
   trade a guild, a hall a ward, a square an exchange, a workshop a
   manufactory, a byre a dairy stall, a well an aqueduct, a lane a road, a
   festival a fair, a smallholding a tenement, a saying an inscription over a
   gate. The chain is six deep: town ← village ← leaf ← mould ← pattern ← loom.
   The page reads the village's own saved state: its households are the
   town's first citizens. Nothing is written by hand.
       node town.mjs
*/
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync } from 'node:fs';
const V = readdirSync('templates-village').filter(f => f.endsWith('.json')).map(f => JSON.parse(readFileSync('templates-village/' + f, 'utf8')));
rmSync('templates-town', { recursive: true, force: true }); mkdirSync('templates-town');
const T = [];
for (const v of V) { let t = null;
  if (v.kind === 'trade') t = { kind: 'guild', name: `the guild of ${v.good}`, dues: v.pays * 3, members: 3, cost: v.cost * 3, text: `${v.good}, by charter. Three households in the guild; dues of ${v.pays * 3} HEZE a day.` };
  else if (v.kind === 'hall') t = { kind: 'ward', name: v.name.replace('the hall over', 'the ward of'), houses: v.houses * 4, cost: v.cost * 3, text: `${v.houses * 4} households in the ward.` };
  else if (v.kind === 'square') t = { kind: 'exchange', name: v.name.replace('the square at', 'the exchange at'), every: v.every, mul: +(v.mul * 1.2).toFixed(2), cost: v.cost * 3, text: `The guilds sell at ×${(v.mul * 1.2).toFixed(2)} every ${v.every} days.` };
  else if (v.kind === 'workshop') t = { kind: 'manufactory', name: v.name.replace("'s shop", "'s manufactory"), mul: +(v.mul * v.mul).toFixed(2), cost: v.cost * 3, text: `Dues ×${(v.mul * v.mul).toFixed(2)}.` };
  else if (v.kind === 'byre') t = { kind: 'stall', name: `the ${v.good} stall`, feeds: 3, cost: v.cost * 2, text: `${v.good} in the market. Feeds three households.` };
  else if (v.kind === 'well') t = { kind: 'aqueduct', name: v.name.replace('the well at', 'the aqueduct from'), waters: v.waters * 5, cost: v.cost * 4, text: `Water, free, for ${v.waters * 5} households. Still nobody pays for water.` };
  else if (v.kind === 'lane') t = { kind: 'road', name: v.name.replace('the lane along', 'the road past'), keep: +Math.min(0.99, v.keep + 0.05).toFixed(2), cost: v.cost * 3, text: `A road; the town loses ×${Math.min(0.99, v.keep + 0.05).toFixed(2)} less to it.` };
  else if (v.kind === 'festival') t = { kind: 'fair', name: v.name.replace('the festival of', 'the fair of'), mul: +(v.mul + 0.1).toFixed(2), text: `Prosperity ×${(v.mul + 0.1).toFixed(2)} for the season.` };
  else if (v.kind === 'holding') t = { kind: 'tenement', name: v.name.replace('the smallholding on', 'the tenement on'), rent: v.grows * 2, cost: v.cost * 2, text: `Rent of ${v.grows * 2} HEZE a day from ${v.grows} of yield that used to be free.` };
  else if (v.kind === 'saying') t = { kind: 'inscription', name: v.name.replace('a saying about', 'the inscription over the gate of'), text: v.text };
  if (t) { t.id = `t-${v.id}`; t.wovenBy = v.id; t.chain = [v.id, ...v.chain]; T.push(t); writeFileSync(`templates-town/${t.id}.json`, JSON.stringify(t, null, 1)); } }
const by = k => T.filter(t => t.kind === k);
const DEF = { guilds: by('guild'), wards: by('ward'), exchanges: by('exchange'), manufactories: by('manufactory'), stalls: by('stall'), aqueducts: by('aqueduct'), roads: by('road'), fairs: by('fair'), tenements: by('tenement'), inscriptions: by('inscription') };
console.log(`town: ${T.length} templates from ${V.length} village templates`);
const page = readFileSync('town.page.js', 'utf8');
const html = `<title>The town &middot; built from the village</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!--
  THE TOWN — the interface after the village. Generated by town.mjs from templates-town/ (${T.length}),
  each woven from a village template, woven from a farm leaf, from a mould, a pattern, a loom:
  six deep. The page reads the village's saved state: its households are the first citizens.
  Guilds pay dues, wards house, aqueducts water for nothing, roads keep, fairs lift, tenements
  charge rent for what used to be free and the page says so. A tower with no windows.
  SCRIPT: yes, and marked.
-->
<style>
  :root{--void:#0b0d12;--panel:#151922;--panel2:#1c2230;--edge:#2b3445;--ink:#efe9dc;--dim:#95a0b3;--gold:#f2c98a;--ok:#6fd4a8;--bad:#e06f5a;--sea:#3f8fbf;--serif:"Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif}
  *{box-sizing:border-box}html,body{margin:0;background:var(--void);color:var(--ink);font:14px/1.55 ui-rounded,system-ui,-apple-system,sans-serif}
  header{padding:22px 24px 10px;max-width:1120px;margin:0 auto;display:flex;align-items:baseline;gap:14px;flex-wrap:wrap}header h1{margin:0;font:500 30px/1.1 var(--serif);color:var(--gold)}header small{color:var(--dim);font-size:13px}header .sp{flex:1}
  #scene{display:block;width:100%;max-width:1120px;height:260px;margin:0 auto;border-radius:14px;background:#0d1626}
  main{padding:14px 24px 40px;max-width:1120px;margin:0 auto;display:grid;gap:14px}
  .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.stat{background:var(--panel);border:1px solid var(--edge);border-radius:12px;padding:10px 12px}.stat b{display:block;font-size:10.5px;color:var(--dim);font-weight:500;text-transform:uppercase;letter-spacing:.08em}.stat span{font:500 22px/1.2 var(--serif);font-variant-numeric:tabular-nums}.stat i{font-style:normal;color:var(--dim);font-size:11.5px;display:block;margin-top:2px}
  .cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media (max-width:860px){.cols{grid-template-columns:1fr}}
  section{background:var(--panel);border:1px solid var(--edge);border-radius:14px;padding:14px}section h2{margin:0 0 8px;font:500 17px/1.2 var(--serif)}section h2 i{font:400 11.5px/1.4 ui-rounded,system-ui,sans-serif;color:var(--dim);display:block;margin-top:2px}
  .card{background:var(--panel2);border:1px solid var(--edge);border-radius:12px;padding:9px 12px;margin:6px 0;display:grid;grid-template-columns:1fr auto;gap:2px 10px;align-items:center;transition:border-color .15s}.card:hover{border-color:#3a4660}.card.done{border-color:var(--ok)}.card b{font-weight:600}.card p{margin:0;color:var(--dim);font-size:12px;grid-column:1}.card .n{grid-row:span 2;font-size:12px;color:var(--gold);text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}
  button{font:inherit;color:var(--ink);background:var(--panel2);border:1px solid var(--edge);border-radius:9px;padding:6px 12px;cursor:pointer}button:hover:not(:disabled){border-color:var(--gold)}button:disabled{opacity:.4;cursor:not-allowed}
  .row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.log{font-size:12px;color:var(--dim);max-height:200px;overflow:auto}.log div{border-bottom:1px solid var(--edge);padding:3px 0}.log b{color:var(--ink);font-weight:500;margin-right:6px}
  .saying{font:italic 15px/1.5 var(--serif);color:var(--gold);margin:0}.chain{font-size:11px;color:var(--dim)}.chain code{color:var(--sea)}
  footer{padding:10px 24px 28px;color:var(--dim);font-size:12px;max-width:1120px;margin:0 auto}footer a{color:var(--sea);text-decoration:none}
</style>
<header><h1>The town</h1><small>built from the village · the chain is six deep · one day a second</small><span class="sp"></span><small id="clock"></small></header>
<canvas id="scene" width="1120" height="260"></canvas>
<main>
  <div class="stats" id="stats"></div>
  <section><p class="saying" id="saying"></p><p style="margin:4px 0 0;color:var(--dim);font-size:12px" id="saying-from"></p></section>
  <div class="cols">
    <div><section><h2>Guilds<i>by charter; three households each, dues a day</i></h2><div id="guilds"></div></section><section><h2>Wards, aqueducts, roads<i>rooms, water for nothing, roads that keep</i></h2><div id="civic"></div></section></div>
    <div><section><h2>Exchanges, manufactories, stalls, tenements<i>what lifts the dues and what charges rent</i></h2><div id="more"></div></section><section><h2>The record</h2><div class="log" id="log"></div><div class="row" style="margin-top:8px"><button id="wipe">Unbuild the town</button></div></section><section><h2>The chain<i>six deep</i></h2><div class="chain" id="chain">Click a building.</div></section></div>
  </div>
</main>
<footer>Templates in templates-town/, each naming its village template; the citizens come from <a href="village.html">the village</a>; the docket from <a href="descent.html">the ground landing</a>. Nothing here is money. <a href="arcade.html">← the arcade</a> · <a href="index.html">the yard</a></footer>
<script id="def-json" type="application/json">${JSON.stringify(DEF).replace(/<\//g, '<\\/')}</script>
<script>
${page}
</script>
`;
writeFileSync('town.html', html); console.log(`wrote town.html (${html.length} bytes)`);
